
// tag::DE[]
== Grundbegriffe

|===
| Dauer: 120 Min. | Übungszeit: Keine
|===


=== Wesentliche Begriffe
{glossary_url}software-architecture[Softwarearchitektur];
Architekturdomänen; 
{glossary_url}structure[Struktur]; 
{glossary_url}building-block[Bausteine]; 
{glossary_url}component[Komponenten]; 
{glossary_url}interface[Schnittstellen]; 
{glossary_url}relationship[Beziehungen]; 
Querschnittskonzepte; 
Nutzen von Softwarearchitektur; 
Softwarearchitekt:innen und deren Verantwortlichkeiten; 
Rolle; 
Aufgaben und benötigte Fähigkeiten; 
Stakeholder und deren Anliegen; 
Anforderungen; 
{glossary_url}constraints[Randbedingungen]; 
Einflussfaktoren; 
Typen von IT-Systemen (eingebettete Systeme; Echtzeitsysteme; Informationssysteme etc.)

// end::DE[]

// tag::EN[]
== Basic Concepts of Software Architecture

|===
| Duration: 120 min. | Exercises: none
|===

=== Relevant Terms
{glossary_url}software-architecture[Software architecture]; 
architecture domains; {glossary_url}structure[structure]; 
{glossary_url}building-block[building blocks]; 
{glossary_url}component[components]; 
{glossary_url}interface[interfaces]; 
{glossary_url}relationship[relationships]; 
{glossary_url}cross-cutting-concepts[cross-cutting-concepts]; 
software architects and their responsibilities; 
tasks and required skills; 
stakeholders and their concerns; 
requirements;
{glossary_url}constraints[constraints]; 
influencing factors; 
types of IT systems (embedded systems; real-time systems; information systems etc.)

// end::EN[]

