// tag::FEEDBACK[]
:filename: 01-basics/01-basics-duration-terms.adoc
include::../config/_feedback.adoc[]
// end::FEEDBACK[]

// tag::DE[]
== Grundbegriffe

|===
| Dauer: 120 Min. | Übungszeit: keine
|===


=== Wesentliche Begriffe
{glossary_url}software-architecture[Softwarearchitektur];
Architekturdomänen; {glossary_url}structure[Struktur]; {glossary_url}building-block[Bausteine], {glossary_url}component[Komponenten]; {glossary_url}interface[Schnittstellen]; {glossary_url}relationship[Beziehungen]; Querschnittskonzepte; Nutzen von Softwarearchitektur; Softwarearchitekten und deren Verantwortlichkeiten; Rolle; Aufgaben und benötigte Fähigkeiten; Stakeholder und deren Anliegen; funktionale Anforderungen; {glossary_url}quality-requirement[Qualitätsanforderungen]; {glossary_url}constraints[Randbedingungen]; Einflussfaktoren; Typen von IT-Systemen (eingebettete Systeme; Echtzeitsysteme; Informationssysteme etc.)

// end::DE[]

// tag::EN[]
== Basic concepts of software architecture

|===
| Duration: 120 Min. | Exercises: none
|===

=== Terms and concepts
{glossary_url}software-architecture[Software architecture]; architecture domains; {glossary_url}structure[structure]; {glossary_url}building-block[building blocks], {glossary_url}component[components]; {glossary_url}interface[interfaces]; {glossary_url}relationship[relationships]; cross-cutting concerns; software architects and their responsibilities; tasks and required skills; stakeholders and their concerns; functional and {glossary_url}quality-requirement[quality] requirements of systems; {glossary_url}constraints[constraints]; influencing factors; types of IT systems (embedded systems; real-time systems; information systems etc.)


// end::EN[]

// tag::REMARK[]
// end::REMARK[]
