
// tag::DE[]
== Grundbegriffe

|===
| Dauer: 120 Min. | Übungszeit: Keine
|===


=== Zielstellung
Ziel dieses Abschnitts ist es, den Teilnehmenden ein grundlegendes Verständnis der wichtigsten Begriffe und Konzepte von Softwarearchitektur zu vermitteln.
Sie werden in die Lage versetzt, verschiedene Definitionen zu diskutieren, die wesentlichen Ziele und Vorteile von Softwarearchitektur zu verstehen und die wichtigsten Aufgaben und Verantwortlichkeiten von Softwarearchitektinnen und Softwarearchitekten zu erkennen.
Außerdem wird deren Rolle im organisatorischen Kontext und ihre Interaktion mit anderen Stakeholdern thematisiert, um es den Teilnehmenden zu ermöglichen, einen effektiven Beitrag zu verschiedenartigen Softwareentwicklungsprojekten zu leisten.

=== Wesentliche Begriffe
{glossary_url}software-architecture[Softwarearchitektur];
Architekturdomänen; 
{glossary_url}structure[Struktur]; 
{glossary_url}building-block[Bausteine]; 
{glossary_url}component[Komponenten]; 
{glossary_url}interface[Schnittstellen]; 
{glossary_url}relationship[Beziehungen]; 
Querschnittsthemen; 
Nutzen von Softwarearchitektur; 
Softwarearchitekt:innen und deren Verantwortlichkeiten; 
Rolle; 
Aufgaben und benötigte Fähigkeiten; 
Stakeholder und deren Anliegen; 
Anforderungen; 
{glossary_url}constraints[Randbedingungen]; 
Einflussfaktoren; 
Typen von IT-Systemen (eingebettete Systeme; Echtzeitsysteme; Informationssysteme etc.)

// end::DE[]

// tag::EN[]
== Basic Concepts of Software Architecture

|===
| Duration: 120 min. | Exercises: none
|===


=== Purpose
The purpose of this section is to equip training participants with a foundational understanding of key terms and concepts in software architecture.
It aims to enable them to discuss various definitions, comprehend the essential goals and benefits, and recognize the critical tasks and responsibilities of software architects. Additionally, the section explores the role of software architects in the broader architectural context and their interactions with other stakeholders, preparing participants to effectively contribute to diverse software development projects.

=== Relevant Terms
{glossary_url}software-architecture[Software architecture]; 
architecture domains; {glossary_url}structure[structure]; 
{glossary_url}building-block[building blocks]; 
{glossary_url}component[components]; 
{glossary_url}interface[interfaces]; 
{glossary_url}relationship[relationships]; 
{glossary_url}cross-cutting-concerns[cross-cutting-concerns]; 
software architects and their responsibilities; 
tasks and required skills; 
stakeholders and their concerns; 
requirements;
{glossary_url}constraints[constraints]; 
influencing factors; 
types of IT systems (embedded systems; real-time systems; information systems etc.)

// end::EN[]

