// tag::FEEDBACK[]
:filename: 01-basics/01-basics-duration-terms.adoc
include::../config/_feedback.adoc[]
// end::FEEDBACK[]

// tag::DE[]
== Grundbegriffe

|===
| Dauer: 120 Min. | Übungszeit: keine
|===


=== Wesentliche Begriffe
Softwarearchitektur, Architekturdomänen, Struktur, Bausteine/Komponenten, Schnittstellen, Beziehungen, Querschnittskonzepte, Nutzen von Softwarearchitektur, Softwarearchitekten und deren Verantwortlichkeiten, Rolle, Aufgaben und benötigte Fähigkeiten, Stakeholder und deren Anliegen, funktionale Anforderungen, Qualitätsanforderungen, Randbedingungen, Einflussfaktoren, Typen von IT-Systemen (eingebettete Systeme, Echtzeitsysteme, Informationssysteme etc.)

// end::DE[]

// tag::EN[]
== Basic concepts of software architecture

|===
| Duration: 120 Min. | Exercises: keine
|===

=== Terms and concepts
Software architecture; architecture domains, structure; building blocks/components; interfaces; relationships; cross-cutting concerns; architecture objectives; software architects and their responsibilities; tasks and required skills; stakeholders and their concerns; functional and quality requirements of systems; constraints; influencing factors; types of IT systems (embedded systems, real-time systems, information systems etc.)


// end::EN[]

// tag::REMARK[]
// end::REMARK[]
