
// tag::DE[]
== Grundbegriffe von Softwarearchitektur

|===
| Dauer: 120 Min. | Übungszeit: Keine
|===


=== Zielsetzung
Ziel dieses Abschnitts ist es, den Teilnehmenden ein grundlegendes Verständnis der wichtigsten Begriffe und Konzepte von Softwarearchitektur zu vermitteln.
Sie lernen verschiedene Definitionen und deren Gemeinsamkeiten kennen, verstehen die wesentlichen Ziele und Vorteile von Softwarearchitektur und können diese anderen Stakeholdern vermitteln.
Weiterhin können sie die wichtigsten Aufgaben und Verantwortlichkeiten von Softwarearchitektinnen und Softwarearchitekten benennen und erklären.
Außerdem wird deren Rolle im organisatorischen Kontext und ihre Interaktion mit anderen Stakeholdern thematisiert, um es den Teilnehmenden zu ermöglichen, einen effektiven Beitrag zu verschiedenartigen Softwareentwicklungsprojekten zu leisten.

=== Wesentliche Begriffe
{glossary_url}software-architecture[Softwarearchitektur];
Architekturdomänen; 
{glossary_url}structure[Struktur]; 
{glossary_url}building-block[Bausteine]; 
{glossary_url}component[Komponenten]; 
{glossary_url}interface[Schnittstellen]; 
{glossary_url}relationship[Beziehungen]; 
{glossary_url}cross-cutting-concern[Querschnittsthemen];
Nutzen von Softwarearchitektur; 
Softwarearchitekt:innen und deren Verantwortlichkeiten; 
Rolle; 
Aufgaben und benötigte Fähigkeiten; 
Stakeholder und deren Anliegen; 
Anforderungen; 
{glossary_url}constraints[Randbedingungen]; 
Einflussfaktoren; 
Typen von IT-Systemen (eingebettete Systeme; Echtzeitsysteme; Informationssysteme etc.)

// end::DE[]

// tag::EN[]
== Basic Concepts of Software Architecture

|===
| Duration: 120 min. | Exercises: none
|===


=== Purpose
The purpose of this section is to equip training participants with a foundational understanding of key terms and concepts in software architecture.
They become familiar with various definitions and their commonalities, understand the essential goals and benefits of software architecture and can communicate these to other stakeholders.
Furthermore, they will be able to name and explain the most important tasks and responsibilities of software architects.
Additionally, the section explores the role of software architects in the broader architectural context and their interactions with other stakeholders, preparing participants to effectively contribute to diverse software development projects.

=== Relevant Terms
{glossary_url}software-architecture[Software architecture]; 
architecture domains; {glossary_url}structure[structure]; 
{glossary_url}building-block[building blocks]; 
{glossary_url}component[components]; 
{glossary_url}interface[interfaces]; 
{glossary_url}relationship[relationships]; 
{glossary_url}cross-cutting-concern[cross-cutting concerns];
software architects and their responsibilities; 
tasks and required skills; 
stakeholders and their concerns; 
requirements;
{glossary_url}constraints[constraints]; 
influencing factors; 
types of IT systems (embedded systems; real-time systems; information systems etc.)

// end::EN[]

