
// tag::DE[]
[[LG-01-06]]
==== LZ 01-06: Bedeutung von Daten und Datenmodellen (R2)

Softwarearchitekt:innen verstehen die Bedeutung von Daten und Datenmodellen für die Architektur.  
Sie

* können Datenmodelle identifizieren, die maßgeblichen Einfluss auf die Architektur haben. 
* können solche Datenmodelle systematisch entwerfen. 
* verstehen den Unterschied zwischen {glossary_url}product[Produkten] und {glossary_url}sum[Summen] in der Datenmodellierung.
* verstehen die Bedeutung der Entkopplung von Datenmodellen und ihrer Repräsentation in Datenbanken, Dateien und Übertragungsprotokollen. 
* können die Auswirkungen von Daten auf Architekturentscheidungen z.B. in Bezug auf Speicherung, Sicherheit, Skalierbarkeit, Zuverlässigkeit, Performance usw. erläutern. 

// end::DE[]

// tag::EN[]
[[LG-01-06]]
==== LG 01-06: Importance of Data and Data Models (R2)

Software architects understand the importance of data and data models for the architecture.  
They

* can identify data models that have significant impact on the  architecture. 
* can design such data models systematically. 
* understand the difference between {glossary_url}product[products] and {glossary_url}sum[sums] in data modelling.
* understand the importance of decoupling data models from their representation in databases, files, and transmission protocols.
* can explain the impact of data on architecture decisions regarding e.g. storage, security, scalability, reliability, performance etc.

// end::EN[]

===== {references}
<<felleisenetal>>, <<sperberklaeren>>, <<kleppmann>>, <<fordhardparts>>
