
// tag::DE[]
[[LG-01-06]]
==== LZ 01-06: Rolle von Softwarearchitekt:innen mit anderen Stakeholdern in Beziehung setzen (R1)
Softwarearchitekt:innen können ihre Rolle erklären. 
Sie sollten ihren Beitrag zur Systementwicklung in Verbindung mit anderen Stakeholdern und Organisationseinheiten kontextspezifisch ausgestalten, insbesondere zu:

* Produktmanagement, Product-Owner
* Projektleitung und -management
* Anforderungsanalytiker:innen (System-/Businessanalyse, Anforderungsmanagement, Fachbereich)
* Entwicklung
* Qualitätssicherung und Test
* IT-Betrieb (Produktion, Rechenzentren), zutreffend primär für Informationssysteme
* Hardwareentwicklung und Systemarchitektur, zutreffend primär für eingebettete und hardwarenahe Systeme
* Unternehmensarchitektur, Architekturboard.

// end::DE[]

// tag::EN[]
[[LG-01-06]]
==== LG 01-06: Relate the Role of Software Architects to Other Stakeholders (R1)
Software architects are able to explain their role. 
They should adapt their contribution to system development depending on the specific context and in relation to other stakeholders and organizational units, in particular to:

* product management and product owners
* project managers
* requirement engineers (requirements- or business analysts, requirements managers, system analysts, business owners, subject-matter experts, etc.)
* developers
* quality assurance and testers
* IT operators and administrators (applies primarily to production environment or data centers for information systems),
* hardware developers and system architects (applies primarily to embedded and hardware-related systems)
* enterprise architects and architecture board members

// end::EN[]
