
// tag::DE[]
[[LG-01-01]]
==== LZ 01-01: Definitionen von Softwarearchitektur diskutieren (R1)
Softwarearchitekt:innen kennen die Gemeinsamkeiten vieler Definitionen
von Softwarearchitektur <<iso42010>> <<bass>> <<kruchten>>:

* Komponenten/Bausteine mit Schnittstellen und Beziehungen
* Bausteine als allgemeiner Begriff, Komponenten als eine spezielle Ausprägung davon
* Strukturen, Querschnittsthemen, Prinzipien
* Architekturentscheidungen und ihre Auswirkungen auf das gesamte System und
  seinen Lebenszyklus

// end::DE[]

// tag::EN[]
[[LG-01-01]]
==== LG 01-01: Discuss Definitions of Software Architecture (R1)

Software architects know the commonalities of many definitions of
software architecture <<iso42010>> <<bass>> <<kruchten>>:

* components/building blocks with interfaces and relationships
* building blocks as a general term, components as a special form thereof
* structures, cross-cutting concerns, principles
* architecture decisions and their consequences on the entire systems and its lifecycle

// end::EN[]
