
// tag::DE[]
[[LZ-01-05]]
==== LZ 01-05 [ehemaliges LZ 1-03]: Softwarearchitektur in Software-Lebenszyklus einordnen (R2)

Softwarearchitekt:innen können Ihre Aufgaben und Ergebnisse in den gesamten Lebenszyklus von IT-Systemen einordnen.
Sie können:

* Konsequenzen von Änderungen bei Anforderungen, Technologien oder der Systemumgebung im Bezug auf die Softwarearchitektur erkennen
* inhaltliche Zusammenhänge zwischen IT-Systemen und den unterstützten Geschäfts- und Betriebsprozessen aufzeigen

// end::DE[]

// tag::EN[]
[[LG-01-05]]
==== LG 01-05 [previously LG 1-03]: Understand Software Architecture as Part of the Software Lifecycle (R2)

Software architects understand their tasks and can integrate their results into the overall lifecycle of IT systems.
They can:

* identify the consequences of changes in requirements, technologies, or the system environment in relation to software architecture
* elaborate on relationships between IT-systems and the supported business and operational processes

// end::EN[]
