
// tag::DE[]
[[LZ-1-9]]
==== LZ 1-9: Zuständigkeit von Softwarearchitekt:innen in organisatorischen Kontext einordnen (R3)

Der Fokus des iSAQB CPSA-Foundation Level liegt auf Strukturen und Konzepten einzelner Softwaresysteme.

Darüber hinaus kennen Softwarearchitekt:innen weitere Architekturdomänen, beispielsweise:

* Unternehmens-IT-Architektur (_Enterprise IT Architecture_): Struktur von Anwendungslandschaften
* Geschäfts- bzw. Prozessarchitektur (_Business and Process Architecture_): Struktur von u.a. Geschäftsprozessen
* Informationsarchitektur: systemübergreifende Struktur und Nutzung von Information und Daten
* Infrastruktur- bzw. Technologiearchitektur: Struktur der technischen Infrastruktur, Hardware, Netze etc.
* Hardware- oder Prozessorarchitektur (für hardwarenahe Systeme)

Diese Architekturdomänen sind nicht inhaltlicher Fokus vom CPSA-F.

// end::DE[]

// tag::EN[]
[[LG-1-9]]
==== LG 1-9: Responsibilities of software architects within the greater architectural context (R3)

The focus of the iSAQB CPSA Foundation Level is on structures and concepts of individual software systems.

In addition, software architects are familiar with other architectural domains, for example:

* enterprise IT architecture: Structure of application landscapes
* business and Process Architecture: Structure of, among other things, business processes
* information architecture: cross-system structure and use of information and data
* infrastructure or technology architecture: Structure of the technical infrastructure, hardware, networks, etc.
* hardware or processor architecture (for hardware-related systems)

These architectural domains are not the content focus of CPSA-F.
// end::EN[]

// tag::REMARK[]
GS, May 31st 2019: The previous wording was difficult to understand, so I rephrased a bit. See https://github.com/isaqb-org/curriculum-foundation/issues/53[issue #53]
// end::REMARK[]
