// tag::FEEDBACK[]
:filename: 01-basics/LZ-1-01.adoc
include::../config/_feedback.adoc[]
// end::FEEDBACK[]

// tag::DE[]
[[LZ-1-1]]
==== LZ 1-1: Definitionen von Softwarearchitektur diskutieren (R1)
Softwarearchitekten kennen mehrerer Definitionen von Softwarearchitektur (u. a. ISO 42010/IEEE 1471, SEI, Booch etc.) und können deren Gemeinsamkeiten benennen:

* Komponenten/Bausteine mit Schnittstellen und Beziehungen
* Bausteine als allgemeiner Begriff, Komponenten als eine spezielle Ausprägung davon
* Strukturen, Querschnittskonzepte, Prinzipien
* Architekturentscheidungen mit systemweiten oder den gesamten Lebenszyklus betreffenden Konsequenzen

// end::DE[]

// tag::EN[]
[[LG-1-1]]
==== LG 1-1: Discuss definitions of software architecture (R1)

Software architects know several definitions of software architecture (incl. ISO 42010/IEEE 1471, SEI, Booch etc.) and can name their similarities:

* Components/building blocks with interfaces and relationships
* building blocks as a general term, components as a special form thereof
* Structures, crosscutting concepts, principles
* Architecture decisions and their consequences on the entire systems and its lifecycle
// end::EN[]

// tag::REMARK[]
// end::REMARK[]
