// tag::FEEDBACK[]
:filename: 01-basics/LZ-1-03.adoc
include::../config/_feedback.adoc[]
// end::FEEDBACK[]

// tag::DE[]
[[LZ-1-3]]
==== LZ 1-3: Softwarearchitektur in Software-Lebenszyklus einordnen (R2)

Softwarearchitekten können Ihre Aufgaben und Ergebnisse in den gesamten Lebenszyklus von IT-Systemen einordnen.
Sie können:

* Konsequenzen von Änderungen bei Anforderungen, Qualitätszielen, Technologien oder der Systemumgebung im Bezug auf die Softwarearchitektur erkennen;
* inhaltliche Zusammenhänge zwischen IT-Systemen und den unterstützten Geschäfts- und Betriebsprozessen aufzeigen.

// end::DE[]

// tag::EN[]
[[LG-1-3]]
==== LG 1-3: Understand software architecture as part of the software life cycle (R2)

Software architects understand their tasks and can integrate their results into the overall lifeycle of IT systems.
They can:

* identify the consequences of changes in requirements, quality objectives, technologies, or the system environment in relation to software architecture;
* elaborate on relationships between IT-systems and the supported business and operational processes.

// end::EN[]

// tag::REMARK[]

[NOTE]
====
GS (April 2019, in reaction to remarks from RR): Aligned DE and EN versions, changed order of items, slightly rephrased second item. Removed references to DWH and other kinds of information systems, as it didn't fit the contents of this LG.

GS (Feb 2019): I'd prefer to replace "in die gesamte Entwicklung" by "Lifecycle" (intro sentence)
====

// end::REMARK[]
