
// tag::DE[]
[[LZ-1-2]]
==== LZ 1-2: Nutzen und Ziele von Softwarearchitektur verstehen und erläutern (R1)

Softwarearchitekt:innen können folgenden Nutzen und wesentlichen Ziele von Softwarearchitektur begründen:

* Entwurf, Implementierung, Pflege und Betrieb von Systemen zu unterstützen
* Qualitätsanforderungen wie Zuverlässigkeit, Wartbarkeit, Änderbarkeit, Sicherheit zu erreichen
* funktionale Anforderungen zu erreichen bzw. deren Erfüllbarkeit sicherzustellen
* Verständnis für Strukturen und Konzepte des Systems zu vermitteln, bezogen auf sämtliche relevanten Stakeholder
* systematisch Komplexität zu reduzieren 
* architekturrelevante Richtlinien für Implementierung und Betrieb zu spezifizieren

// end::DE[]

// tag::EN[]
[[LG-1-2]]

==== LG 1-2: Understand and explain the goals and benefits of software architecture (R1)

Software architects can justify the following essential goals and benefits of software architecture:

* support the design, implementation, maintenance, and operation of systems
* achieve quality requirements such as reliability, maintainability, changeability, security, etc.
* achieve functional requirements or ensure that they can be met
* ensure that the the system's structures and concepts are understood by all relevant stakeholders
* systematically reduce complexity
* specify architecturally relevant guidelines for implementation and operation
 
// end::EN[]

// tag::REMARK[]
[NOTE]
====
GS, August 2019: after discussions and comments from Andreas Rausch and Mahbouba Gharbi, re-formulated first item (removed "in contrast to functionality").
GS/CL: sprachlich leicht umformuliert

RR: Keine klare Abgrenzung zwischen Nutzen und Zielen, deswegen vereinfacht.
====
// end::REMARK[]
