
// tag::DE[]
[[LZ-1-5]]
==== LZ 1-5: Rolle von Softwarearchitekten in Beziehung zu anderen Stakeholdern setzen (R1)
Softwarearchitekten können ihre Rolle erklären und ihren Beitrag zur Systementwicklung in Verbindung mit anderen Stakeholdern kontextspezifisch ausgestalten, insbesondere zu:

* Anforderungsanalyse (Systemanalyse, Anforderungsmanagement, Fachbereich)
* Implementierung
* Projektleitung und -management
* Produktmanagement, Product-Owner
* Qualitätssicherung
* IT-Betrieb (Produktion, Rechenzentren), zutreffend primär für Informationssysteme
* Hardwareentwicklung
* Unternehmensarchitektur, Architekturboard.

// end::DE[]

// tag::EN[]
[[LG-1-5]]
==== LG 1-5: Relate the role of software architects to other stakeholders (R1)
Software architects are able to explain their role.
They should adapt their contribution to a software development in a specific context and in relation to other stakeholders, in particular to:

* Requirements analysis (system analysis, requirements management, specialist field)
* Implementation
* Project lead and management
* Product management, product owner
* Quality assurance
* IT operations (production, data centers), applies primarily to information systems
* Hardware development
* Enterprise architecture, architecture board.

// end::EN[]

// tag::REMARK[]
// end::REMARK[]
