// tag::FEEDBACK[]
:filename: 01-basics/LZ-1-06.adoc
include::../config/_feedback.adoc[]
// end::FEEDBACK[]

// tag::DE[]
[[LZ-1-6]]
==== LZ 1-6: Zusammenhang zwischen Entwicklungsvorgehen und Softwarearchitektur erläutern können (R1)

* Softwarearchitekten können den Einfluss von iterativem Vorgehen auf Architekturentscheidungen erläutern (hinsichtlich Risiken und Prognostizierbarkeit);
* Sie müssen aufgrund inhärenter Unsicherheit oftmals iterativ arbeiten und entscheiden.
Dabei müssen sie bei anderen Stakeholdern systematisch Rückmeldung einholen.

// end::DE[]

// tag::EN[]
[[LG-1-6]]
==== LG 1-6: Can explain the correlation between development approaches and software architecture (R1)

* Software architects are able to explain the influence of iterative approaches on architectural decisions (with regard to risks and predictability)
* Due to inherent uncertainty, software architects often have to work and make decisions iteratively. To do so, they have to systematically obtain feedback from other stakeholders.

// end::EN[]


// tag::REMARK[]
// end::REMARK[]
