
// tag::DE[]
[[LZ-1-1]]
==== LZ 1-1: Definitionen von Softwarearchitektur diskutieren (R1)
Softwarearchitekt:innen kennen mehrere Definitionen von Softwarearchitektur (u. a. ISO 42010/IEEE 1471, SEI, Booch etc.) und können deren Gemeinsamkeiten benennen:

* Komponenten/Bausteine mit Schnittstellen und Beziehungen
* Bausteine als allgemeiner Begriff, Komponenten als eine spezielle Ausprägung davon
* Strukturen, Querschnittskonzepte, Prinzipien
* Architekturentscheidungen mit systemweiten oder den gesamten Lebenszyklus betreffenden Konsequenzen

// end::DE[]

// tag::EN[]
[[LG-1-1]]
==== LG 1-1: Discuss Definitions of Software Architecture (R1)

Software architects know several definitions of software architecture (incl. ISO 42010/IEEE 1471, SEI, Booch etc.) and can name their similarities:

* components/building blocks with interfaces and relationships
* building blocks as a general term, components as a special form thereof
* structures, cross-cutting concepts, principles
* architecture decisions and their consequences on the entire systems and its lifecycle

// end::EN[]
