
// tag::DE[]
[[LZ-1-7]]
==== LZ 1-7: Kurz- und langfristige Ziele differenzieren (R1)

Softwarearchitekt:innen können:

* langfristige Qualitätsanforderungen sowie deren Abgrenzung gegen (kurzfristige) Projektziele erklären
* Potentielle Zielkonflikte zwischen kurz- und langfristigen Zielen erklären, um eine für alle Beteiligten tragfähige Lösung zu erarbeiten
* Qualitätsanforderungen identifizieren und präzisieren

// end::DE[]

// tag::EN[]
[[LG-1-7]]
==== LG 1-7: Differentiate between short- and long-term goals (R1)

Software architects can:

* explain long-term quality requirements and their differentiation from (short-term) project goals
* explain potential conflicts between short-term and long-term goals, in order to find a suitable solution for all stakeholders
* identify and specify quality requirements

// end::EN[]

// tag::REMARK[]
[NOTE]
====
* G.Starke (April 2019): changed order of items. Removed "Architecture goals", added "specify quality requirements" - fixing both https://github.com/isaqb-org/curriculum-foundation/issues/33[issue #33] and https://github.com/isaqb-org/curriculum-foundation/issues/11[issue 11].
* P.Ghadir (April 2019):  add "handle conflicts between short-term and long-term goals", see https://github.com/isaqb-org/curriculum-foundation/issues/33[issue #33] 
* GS/CL (Jan 2019): Begriffe "Architektur- und Projektziele" durch kurz- und langfristige Ziele ersetzt. Formulierung vereinfacht.
* RR: Removed redundancies, especially with LG 2-3
====
// end::REMARK[]
