
// tag::DE[]
[[LZ-1-2]]
==== LZ 1-2: Ziele von Softwarearchitektur verstehen und erläutern (R1)

Softwarearchitekt:innen können folgende wesentlichen Ziele von Softwarearchitektur begründen.

Softwarearchitektur zielt darauf ab: 

* Entwurf, Implementierung, Pflege und Betrieb von Systemen zu unterstützen,
* Qualitätsanforderungen wie Zuverlässigkeit, Wartbarkeit, Änderbarkeit, Sicherheit zu erreichen,
* funktionale Anforderungen zu erreichen bzw. deren Erfüllbarkeit sicherzustellen,
* Verständnis für Strukturen und Konzepte des Systems zu vermitteln, bezogen auf sämtliche relevanten Stakeholder,
* systematisch Komplexität zu reduzieren 
* architekturrelevante Richtlinien für Implementierung und Betrieb zu spezifizieren

// end::DE[]

// tag::EN[]
[[LG-1-2]]

==== LG 1-2: Understand and explain the benefits of software architecture (R1)

Software architects can justify the following essential goals of software architecture.

Software architecture aims at:

* supporting design, implementation, maintenance and operation of systems
* achieving quality requirements such as reliability, maintainability, changeability, security
* achieving functional requirements or ensuring that they can be met
* providing an understanding of the system's structures and concepts, with regard to all relevant stakeholders
* systematically reducing complexity 
* specifying architecturally relevant guidelines for implementation and operation




// end::EN[]

// tag::REMARK[]
[NOTE]
====
GS, August 2019: after discussions and comments from Andreas Rausch and Mahbouba Gharbi, re-formulated first item (removed "in contrast to functionality").
GS/CL: sprachlich leicht umformuliert

RR: Keine klare Abgrenzung zwischen Nutzen und Zielen, deswegen vereinfacht.
====
// end::REMARK[]
