
// tag::DE[]
[[LZ-1-10]]
==== LZ 1-10: Typen von IT-Systemen unterscheiden (R3)

Softwarearchitekt:innen kennen unterschiedliche Typen von IT-Systemen, beispielsweise:

* Informationssysteme
* Decision-Support, Data-Warehouse oder Business-Intelligence Systeme
* Mobile Systeme
* _Cloud-native_ Systeme (siehe <<cncf>>)
* Batchprozesse oder -systeme
* Systeme die auf maschinellem Lernen oder künstlicher Intelligenz basieren
* hardwarenahe Systeme; hier verstehen sie die Notwendigkeit des Hardware-/Software-Codesigns (zeitliche und inhaltliche Abhängigkeiten von Hard- und Softwareentwicklung).


// end::DE[]

// tag::EN[]
[[LG-1-10]]
==== LG 1-10: Differentiate Types of It Systems (R3)

Software architects know different types of IT systems, for example:

* information systems
* decision support, data warehouse or business intelligence systems
* mobile systems
* _Cloud-native_ Systeme (siehe <<cncf>>)
* batch processes or systems
* systems based upon machine learning or artificial intelligence
* hardware-related systems; here they understand the necessity of hardware/software codesign (temporal and content-related dependencies of hardware and software design)

// end::EN[]
