
// tag::DE[]
[[LZ-1-2]]
==== LZ 1-2: Nutzen und Ziele von Softwarearchitektur verstehen und erläutern (R1)

Softwarearchitekt:innen können folgenden Nutzen und wesentlichen Ziele von Softwarearchitektur begründen:

* Entwurf, Implementierung, Pflege und Betrieb von Systemen zu unterstützen
* funktionale Anforderungen zu erreichen bzw. deren Erfüllbarkeit sicherzustellen
* Qualitätsanforderungen wie Zuverlässigkeit, Wartbarkeit, Änderbarkeit, Sicherheit, Energieeffizienz zu erreichen bzw. deren Erfüllbarkeit sicherzustellen
* die Einhaltung von Rahmenbedingungen zu erreichen bzw. deren Erfüllbarkeit sicherzustellen
* Verständnis für Strukturen und Konzepte des Systems zu vermitteln, bezogen auf sämtliche relevanten Stakeholder
* systematisch Komplexität zu reduzieren 
* architekturrelevante Richtlinien für Implementierung und Betrieb zu spezifizieren

// end::DE[]

// tag::EN[]
[[LG-1-2]]

==== LG 1-2: Understand and Explain the Goals and Benefits of Software Architecture (R1)

Software architects can justify the following essential goals and benefits of software architecture:

* support the design, implementation, maintenance, and operation of systems
* achieve functional requirements or ensure that they can be met
* achieve quality requirements, e.g. reliability, maintainability, changeability, security, energy efficiency etc.
* achieve the fulfilment of constraints
* ensure that the the system's structures and concepts are understood by all relevant stakeholders
* systematically reduce complexity
* specify architecturally relevant guidelines for implementation and operation
 
// end::EN[]
