// tag::FEEDBACK[]
:filename: 01-basics/LZ-1-02.adoc
include::../config/_feedback.adoc[]
// end::FEEDBACK[]

// tag::DE[]
[[LZ-1-2]]
==== LZ 1-2: Ziele von Softwarearchitektur verstehen und herausstellen (R1)

Wesentliche Ziele von Softwarearchitektur sind:

* Qualitätsanforderungen wie Zuverlässigkeit, Wartbarkeit, Änderbarkeit, Sicherheit sowie funktionale Anforderungen zu erreichen
* Erstellung und Wartung von Software, insbesondere die Implementierung zu unterstützen
* Verständnis für Strukturen und Konzepte des Systems zu vermitteln, bezogen auf sämtliche relevanten Stakeholder.

// end::DE[]

// tag::EN[]
[[LG-1-2]]
==== LG 1-2: Understand and identify the benefits of software architecture (R1)

Essential goals of software architecture are:

* the achievement of quality requirements such as reliability, maintainability, changeability, security etc. and functional requirements 
* supporting the creation and maintenance of software, particularly its implementation
* convey the understanding of structures and concepts of the system, related to all relevant stakeholders.

// end::EN[]

// tag::REMARK[]
[NOTE]
====
GS, August 2019: after discussions and comments from Andreas Rausch and Mahbouba Gharbi, re-formulated first item (removed "in contrast to functionality").
GS/CL: sprachlich leicht umformuliert

RR: Keine klare Abgrenzung zwischen Nutzen und Zielen, deswegen vereinfacht.
====
// end::REMARK[]
