
// tag::DE[]
== Beschreibung und Kommunikation von Softwarearchitekturen

|===
| Dauer: 180 Min. | Übungszeit: 60 Min.
|===

===	Wesentliche Begriffe

Architektur-)Sichten; Strukturen; (technische) Konzepte; Dokumentation; Kommunikation; Beschreibung; zielgruppen- oder stakeholdergerecht; Meta-Strukturen und Templates zur Beschreibung und Kommunikation; Kontextabgrenzung; Bausteine; Bausteinsicht; Laufzeitsicht; Verteilungssicht; Knoten; Kanal; Verteilungsartefakte; Mapping von Bausteinen auf Verteilungsartefakte; Beschreibung von Schnittstellen und Entwurfsentscheidungen; UML; Werkzeuge zur Dokumentation

// end::DE[]

// tag::EN[]
== Specification and communication of software architectures

|===
| Duration: 180 min. | Exercises: 60 min.
|===

=== Relevant terms
(Architectural) Views; structures; (technical) concepts; documentation; communication; description; stakeholder-oriented, meta structures and templates for description and communication; system context; building blocks; building block view; runtime view; deployment view; node; channel; deployment artifacts; mapping building blocks onto deployment artifacts; description of interfaces and design decisions; UML, tools for documentation
// end::EN[]

// tag::REMARK[]
[NOTE]
====
GS (Feb. 2019): Why do we have ";" semicolons in EN and comma in DE?
====
// end::REMARK[]
