// tag::FEEDBACK[]
:filename: 03-documentation/01-documentation-duration-terms.adoc
include::../config/_feedback.adoc[]
// end::FEEDBACK[]

// tag::DE[]
==	Beschreibung und Kommunikation von Softwarearchitekturen

|===
| Dauer: 150 Min. | Übungszeit: 90 Min.
|===

===	Wichtige Begriffe

Sichten, Strukturen; (technische) Konzepte; Dokumentation; Kommunikation, Beschreibung; zielgruppen- oder stakeholdergerecht; Meta-Strukturen und Templates zur Beschreibung und Kommunikation; Kontextabgrenzung; Bausteine; Bausteinsicht; Laufzeitsicht; Verteilungssicht; Knoten; Kanal; Verteilungsartefakte; Mapping von Bausteinen auf Verteilungsartefakte; Beschreibung von Schnittstellen und Entwurfsentscheidungen; UML, Werkzeuge zur Dokumentation

// end::DE[]

// tag::EN[]
== 3 Specification and communication of software architectures

|===
| Duration: 150 min. | Exercises: 90 min.
|===

=== Terms and concepts
Views; structures; (technical) concepts; documentation; communication; description; stakeholder-oriented, meta structures and templates for description and communication; system context; building blocks; building-block view; runtime view; deployment view; node; channel; deployment artifacts; mapping building blocks onto deployment artifacts; description of interfaces and design decisions; UML, tools for documentation
// end::EN[]

// tag::REMARK[]
[IMPORTANT]
====
GS (Feb. 2019): Why do we have ";" semicolons in EN and comma in DE?
====
// end::REMARK[]
