// tag::DE[]
[[LZ-3-4]]
==== LZ 3-4: Architektursichten erläutern und anwenden (R1)
Softwarearchitekten können folgende Architektursichten anwenden:

* Kontextsicht (auch genannt Kontextabgrenzung)
* Baustein- oder Komponentensicht (Aufbau des Systems aus Softwarebausteinen)
* Laufzeitsicht (dynamische Sicht, Zusammenwirken der Softwarebausteine zur Laufzeit, Zustandsmodelle)
* Verteilungs-/Deploymentsicht (Hardware und technische Infrastruktur sowie Abbildung von Softwarebausteinen auf diese Infrastruktur)

// end::DE[]

// tag::EN[]
[[LG-3-4]]
==== LG 3-4: Explain and use architectural views (R1)
Software architects are able to use the following architectural views:

* Context view 
* Building-block or component view (composition of software building blocks) 
* Run-time view (dynamic view, interaction between software building blocks at run-time, state machines) 
* Deployment view (hardware and technical infrastructure as well as the mapping of software building blocks onto the infrastructure)

// end::EN[]

// tag::REMARK[]
// end::REMARK[]
