// tag::DE[]
[[LZ-3-2]]
==== LZ 3-2: Softwarearchitekturen beschreiben und kommunizieren (R1)

Softwarearchitekt:innen:

* können Architekturen stakeholdergerecht dokumentieren und kommunizieren und dadurch unterschiedliche Zielgruppen adressieren, z. B. Management, Entwicklungsteams, QS, andere Softwarearchitekt:innen sowie möglicherweise zusätzliche Stakeholder
* können die Beiträge unterschiedlicher Autorengruppen stilistisch und inhaltlich konsolidieren und harmonisieren
* kennen den Nutzen von Template-basierter Dokumentation.

Softwarearchitekt:innen wissen, dass verschiedene Eigenschaften der Dokumentation von Spezifika des Systems, seinen Anforderungen, Risiken, dem Entwicklungsvorgehen, der Organisation oder anderen Faktoren abhängen.

Diese Faktoren beeinflussen beispielsweise:

* ob der schriftlichen oder mündlichen Kommunikation Vorrang eingeräumt werden sollte
* Umfang und Detaillierungsgrad der in jeder Entwicklungsphase benötigten Dokumentation
* das Dokumentationsformat
* die Zugänglichkeit der Dokumentation
* Formalitäten der Dokumentation (z.B. Diagramme, die einem Metamodell entsprechen, oder einfache Zeichnungen)
* formale Überprüfungen und Freigabeprozesse für die Dokumentation

Softwarearchitekt:innen sind sich dieser Faktoren bewusst und können die Dokumentationsmerkmale je nach Situation anpassen.



// end::DE[]

// tag::EN[]
[[LG-3-2]]
==== LG 3-2: Describe and communicate software architectures (R1,R3)
Software architects are able to:

* document and communicate architectures for corresponding stakeholders, thereby addressing different target groups, e.g. management, development teams, QA, other software architects, and possibly additional stakeholders
* consolidate and harmonise the style and content of contributions from different groups of authors
* know the benefits of template-based documentation.

Software architects know that various properties of documentation depend on specifics of the system, its requirements, risks, development process, organization or other factors.

These factors impact:

* whether written or verbal communication should be prioritized
* the amount and level of detail of documentation needed at each stage of development
* the documentation format
* the accessibility to the documentation
* formality of documentation (e.g. diagrams compliant to a meta model or simple drawings)
* formal reviews and sign-off processes for documentation

Software architects are aware of these factors and can adjust the documentation characteristics according to the situation.
// end::EN[]

// tag::REMARK[]
[NOTE]
====

GS: Layout, sprachlich vereinfacht, _Schablone_ entfernt
====
// end::REMARK[]
