
// tag::DE[]
[[LZ-3-3]]
==== LZ 3-3: Notations-/Modellierungsmittel f체r Beschreibung von Softwarearchitektur erl채utern und anwenden (R2)

Softwarearchitekten kennen mindestens folgende UML-Diagramme zur Notation von Architektursichten:

* Klassen-, Paket-, Komponenten- und Kompositionsstrukturdiagramme
* Verteilungsdiagramme
* Sequenz- und Aktivit채tsdiagramme
* Zustandsdiagramme

Softwarearchitekten kennen Alternativen zu UML-Diagrammen. Insbesondere f체r die Laufzeitsicht eignen sich z. B. Flussdiagramme, nummerierte Listen, BPMN.

// end::DE[]

// tag::EN[]
[[LG-3-3]]
==== LG 3-3: Explain and apply notations/models to describe software architecture (R2)

Software architects know at least the following UML diagrams to describe architectural views:

* class, package, component and composition-structure diagrams
* deployment diagrams
* sequence and activity diagrams
* state diagrams

Software architects know alternative notations to UML diagrams, especially for the runtime view, 
e.g., flow charts, numbered lists, BPMN.

// end::EN[]

// tag::REMARK[]
// end::REMARK[]
