// tag::DE[]
[[LZ-3-2]]
==== LZ 3-2: Softwarearchitekturen beschreiben und kommunizieren (R1)

Softwarearchitekt:innen (R1):

* können Architekturen stakeholdergerecht dokumentieren und kommunizieren und dadurch unterschiedliche Zielgruppen adressieren, z. B. Management, Entwicklungsteams, QS, andere Softwarearchitekt:innen sowie möglicherweise zusätzliche Stakeholder
* können die Beiträge unterschiedlicher Autorengruppen stilistisch und inhaltlich konsolidieren und harmonisieren
* können Maßnahmen entwickeln und umsetzen, die mündliche und schriftliche Kommunikation in Einklang miteinander halten und miteinander angemessen ausbalancieren
* wissen, dass verschiedene Eigenschaften der Dokumentation von Spezifika des Systems, seinen Anforderungen, Risiken, dem Entwicklungsvorgehen, der Organisation oder anderen Faktoren abhängen.
* kennen den Nutzen von Template-basierter Dokumentation

Diese Faktoren beeinflussen beispielsweise (R3):

* Umfang und Detaillierungsgrad der benötigten Dokumentation
* das Dokumentationsformat
* die Zugänglichkeit der Dokumentation
* Formalitäten der Dokumentation (z.B. Diagramme, die einem Metamodell entsprechen, oder einfache Zeichnungen)
* formale Überprüfungen und Freigabeprozesse für die Dokumentation

Softwarearchitekt:innen sind sich dieser Faktoren bewusst und können die Dokumentationsmerkmale je nach Situation anpassen.



// end::DE[]

// tag::EN[]
[[LG-3-2]]
==== LG 3-2: Describe and Communicate Software Architectures (R1,R3)

Software architects are able to (R1):

* document and communicate architectures for corresponding stakeholders, thereby addressing different target groups, e.g. management, development teams, QA, other software architects, and possibly additional stakeholders
* consolidate and harmonise the style and content of contributions from different groups of authors
* develop and implement measures to support the convergence of written and verbal communication, and balance one against the other appropriately

Software architects know (R1):

* that various properties of documentation depend on specifics of the system, its requirements, risks, development process, organization or other factors.
* the benefits of template-based documentation


These factors impact (R3):

* the amount and level of detail of documentation needed 
* the documentation format
* the accessibility of the documentation
* formality of documentation (e.g. diagrams compliant to a meta model or simple drawings)
* formal reviews and sign-off processes for documentation

Software architects are aware of these factors and can adjust the documentation characteristics according to the situation.

// end::EN[]
