
// tag::DE[]
[[LZ-3-10]]
==== LZ 3-10: Weitere Hilfsmittel und Werkzeuge zur Dokumentation kennen (R3)

Softwarearchitekt:innen kennen:

* Grundlagen mehrerer publizierter Frameworks zur Beschreibung von Softwarearchitekturen, beispielsweise:
** ISO/IEEE-42010 (vormals 1471)
** arc42
** C4
** FMC
* Ideen und Beispiele von Checklisten für die Erstellung, Dokumentation und Prüfung von Softwarearchitekturen
* mögliche Werkzeuge zur Erstellung und Pflege von Architekturdokumentation

// end::DE[]

// tag::EN[]
[[LG-3-10]]
==== LG 3-10: Know additional resources and tools for documentation (R3)

Software architects know:

* basics of several published frameworks for the description of software architectures, for example:
** ISO/IEEE-42010 (formerly 1471)
** arc42
** C4
** FMC
* ideas and examples of checklists for the creation, documentation, and testing of software architectures
* possible tools for creating and maintaining architectural documentation

// end::EN[]

// tag::REMARK[]
[NOTE]
====
GS: (Feb 2019): please can we remove the "checklists"?

GS: C4 aufgenommen (von Simon Brown)

GS/RR: TOGAF entfernt
====
// end::REMARK[]
