
// tag::DE[]
[[LZ-3-8]]
==== LZ 3-8: Architekturentscheidungen erläutern und dokumentieren (R1-R2)

Softwarearchitekt:innen können:

* Architekturentscheidungen systematisch herbeiführen, begründen, kommunizieren und dokumentieren
* gegenseitige Abhängigkeiten solcher Entscheidungen erkennen, kommunizieren und dokumentieren

Softwarearchitekt:innen kennen Architecture-Decision-Records (ADR, siehe <<nygard>>) und können diese zur Dokumentation von Entscheidungen einsetzen (R2).
// end::DE[]

// tag::EN[]
[[LG-3-8]]
==== LG 3-8: Explain and document architectural decisions (R1-R2)

Software architects are able to:

* systematically take, justify, communicate, and document architectural decisions
* identify, communicate, and document interdependencies between design decisions

Software architects know about Architecture-Decision-Records (ADR, see <<nygard>>) and can apply these to document decisions (R2).

// end::EN[]

// tag::REMARK[]
[NOTE]
====
GS (Juni 2019): "herleiten" durch "herbeiführen" ersetzt (engl: derive -> take)

GS (Feb 2019): wording: += kommunizieren, begründen
====

// end::REMARK[]
