// tag::DE[]
[[LZ-3-1]]
==== LZ 3-1: Qualitätsmerkmale technischer Dokumentation erläutern und berücksichtigen (R1)

Softwarearchitekt:innen kennen die wesentlichen Qualitätsmerkmale technischer Dokumentation und können diese bei der Dokumentation von Systemen berücksichtigen bzw. erfüllen:

* Verständlichkeit, Korrektheit, Effizienz, Angemessenheit, Wartbarkeit
* Orientierung von Form, Inhalt und Detailgrad an Zielgruppe der Dokumentation

Sie wissen, dass Verständlichkeit technischer Dokumentation nur von deren Zielgruppen beurteilt werden kann.

// end::DE[]

// tag::EN[]
[[LG-3-1]]
==== LG 3-1: Explain and consider the quality of technical documentation (R1)
Software architects know the quality requirements of technical documentation and can consider and fulfil those when documenting systems:

* Understandability, correctness, efficiency, appropriateness, maintainability
* Form, content, and level of detail tailored to the stakeholders

They know that only the target audiences can assess the understandability of technical documentation.

// end::EN[]

// tag::REMARK[]
[NOTE]
====
GS: _Leser_ durch _Zielgruppe_ ersetzt
====
// end::REMARK[]
