= *DRAFT* https://isaqb.org[iSAQB] Foundation Level Curriculum

Licensed trainings for _Certified Professional for Software Architecture – Foundation Level (CPSA-F)_ will provide participants with the knowledge and skills required to design, specify and document a software architecture adequate to fulfil the respective requirements for small and medium-sized systems. 

This repository contains the *curriculum* for the upcoming version 5 of CPSA-F (which is scheduled for productive use not before July 2019). 

This is <<copyrighted,copyrighted work>>.

== How to contribute or participate
You found a bug in one of the published versions, have remarks, comments or proposals?

TODO: add issue templates for bugs, comments, proposals

== How to build the documents

* build with gradle. That will produce html output only. Should be used for personal development or review work only.
* build with adoc2pdf (which is contained in a distinct repository under the isaqb-org organization)

== Maintainers

The iSAQB members association regularly elects the *Foundation Level Working Group* (FLWG), consisting of maximum 10 people.
The FLWG is responsible for maintaining the CPSA-F Curriculum. Major version updates are discussed with the members association prior to publication.

The current (2019) FLWG members are:

* Dr. Gernot Starke (FLWG chair)
* Phillip Ghadir (FLWG co-chair)
* Dr. Carola Lilienthal
* Mahbouba Gharbi
* Alexander Lorz
* Peter Götz
* Mischa Soujon
* Dr. Ulrich Becker
* Roger Rhoades
* Dr. Peter Hruschka



== Requirements

TODO: describe our requirements

* adressing (nearly) all types of software systems (e.g. embedded-, real-time-, information-, decision-support, business-intelligence- and similar systems)
* relying on defined prerequisites (not covering everything)
* not trying to write a textbook on software architecture
* ...

== History

TODO: add version history from 2008

== Contributors
Work on this curriculum started way back in 2007/2008 - and numerous people contributed - either by proposing, crafting and writing content or by commenting, reviewing and otherwise helping to improve.


[[copyrighted]]
== Licensing and Copyright

THIS IS COPYRIGHTED WORK.

© (Copyright), https://isaqb.org[International Software Architecture Qualification Board e. V.]
(iSAQB® e. V.) 2009-2019

The curriculum may only be used subject to the following conditions:

1. You wish to obtain the CPSA Certified Professional for Software Architecture Foundation Level® certificate. For the purpose of obtaining the certificate, it shall be permitted to use these text documents and/or curricula by creating working copies for your own computer. If any other use of documents and/or curricula is intended, for instance for their dissemination to third parties, for advertising etc., please write to contact@isaqb.org to enquire whether this is permitted. A separate license agreement would then have to be entered into.

2. If you are a trainer, training provider or training organizer, it shall be possible for you to use the documents and/or curricula once you have obtained a usage license.
Please address any enquiries to contact@isaqb.org. License agreements with comprehensive provisions for all aspects exist.

3. If you fall neither into category 1 nor category 2, but would like to use these documents and/or curricula nonetheless, please also contact the iSAQB e. V. by writing to contact@isaqb.org. You will then be informed about the possibility of acquiring relevant licenses through existing license agreements, allowing you to obtain your desired usage authorizations.

We stress that, as a matter of principle, this curriculum is protected by copyright.

The International Software Architecture Qualification Board e. V. (iSAQB® e. V.) has exclusive entitlement to these copyrights.

The abbreviation "e. V." is part of the iSAQB's official name and stands for "eingetragener Verein" (registered association), which describes its status as a legal entity according to German law.
 