
// tag::DE[]

== Entwurf und Entwicklung von Softwarearchitekturen

|===
| Dauer: 330 Min. | Übungszeit: 90 Min.
|===

=== Zielsetzung
Dieser Abschnitt zielt darauf ab, die Teilnehmenden in die Lage zu versetzen, Architekturentscheidungen so zu treffen, dass Anforderungen der Stakeholder unter Berücksichtigung der Randbedingungen erfüllt werden können.
Sie lernen, Architekturentwürfe zu entwickeln, fundierte Entscheidungen zur Systemzerlegung zu treffen und Abhängigkeiten zwischen Bausteinen zu gestalten.
Zu diesem Zweck lernen sie, grundlegende Ansätze und Heuristiken bei der Architekturentwicklung anzuwenden.
Sie erkennen die Bedeutung von Entwurfsprinzipien und Lösungsmustern und können diese anwenden.
Darüber hinaus werden in diesem Abschnitt der Umgang mit Querschnittsthemen, die Prinzipien des Software-Deployments und die Herausforderungen verteilter Systeme thematisiert.

=== Wesentliche Begriffe

Entwurf; 
Vorgehen beim Entwurf; 
Entwurfsentscheidung; 
Sichten; 
{glossary_url}interface[Schnittstellen];
technische Konzepte und Querschnittsthemen; 
Architekturmuster; 
Entwurfsmuster; 
Mustersprachen; 
Entwurfsprinzipien; 
Abhängigkeit; 
Kopplung; 
Kohäsion; 
Top-down- und Bottom-up-Vorgehen;
modellbasierter Entwurf; 
iterativer/inkrementeller Entwurf; 
Domain-Driven Design

// end::DE[]

// tag::EN[]
== Design and Development of Software Architectures

|===
| Duration: 330 min. | Excercises: 90 min.
|===

=== Purpose
This section aims to enable participants to take architectural decisions in a way that fulfills stakeholder requirements while respecting the given constraints of the system context.
They will learn to develop architectural designs, make informed decisions on system decomposition and shape dependencies between building blocks.
To this end, they learn to apply basic approaches and heuristics in architecture development.
They recognize the importance of design principles and solution patterns and are able to apply them.
In addition, this section addresses the management of cross-cutting concerns, the principles of software deployment and the challenges of distributed systems.

=== Relevant Terms
Design; design approach; design decision; views; 
{glossary_url}interface[interfaces];  
technical concepts and
{glossary_url}cross-cutting-concern[cross-cutting concerns];
architectural patterns;
design patterns;
pattern languages; 
design principles; 
dependencies; 
coupling; 
cohesion; 
top-down and bottom-up approaches; 
model-based design; 
iterative/incremental design; 
domain-driven design

// end::EN[]
