
// tag::DE[]
[[LG-03-08]]
==== LZ 03-08 [ehemaliges LZ 2-5]: Wichtige Architekturmuster beschreiben, erklären und angemessen anwenden (R1, R3)

Softwarearchitekt:innen können die folgenden Architekturmuster erklären und Beispiele dafür liefern (R1):

* {glossary_url}layer[Layer]
* {glossary_url}pipes-and-filters[Pipes und Filter]
* {glossary_url}microservices[Microservices]

Softwarearchitekt:innen können einige der folgendene Muster erklären, ihre Relevanz für konkrete Systeme erläutern und Beispiele dafür liefern (R3):

* {glossary_url}blackboard[Blackboard]
* {glossary_url}broker[Broker]
* {glossary_url}cqrs[CQRS (Command-Query-Responsibility-Segregation)]
* {glossary_url}event-sourcing[Event sourcing]
* {glossary_url}dependency-injection[Dependency Injection] (siehe auch <<LG-03-06>>)
* Integrations und Messaging-Patterns (z.B. aus <<hohpe>>)
* {glossary_url}remote-procedure-call[Remote procedure call]
* {glossary_url}model-view-controller[MVC] (Model View Controller),
  {glossary_url}model-view-viewmodel[MVVM] (Model View ViewModel),
  {glossary_url}model-view-update[MVU] (Model View Update),
  {glossary_url}presentation-abstraction-control[PAC] (Presentation Abstraction Control)
* {glossary_url}plugin[Plugin]
* {glossary_url}ports-and-adapters[Ports and Adapters] (Synonyme: Onion Architektur, Hexagonal Architektur, Clean Architektur)
* {glossary_url}service-oriented-architecture[SOA] (Service-Oriented Architektur)

Softwarearchitekt:innen kennen wesentliche Quellen für Architekturmuster, beispielsweise die POSA-Literatur (z.{nbsp}B. <<buschmanna>>) und PoEAA (<<fowler>>) (für Informationssysteme). (R3)


Sie wissen:

* dass Muster ein Weg sind, bestimmte Qualitäten für gegebene Probleme und Anforderungen innerhalb gegebener Kontexte zu erreichen.
* dass es verschiedene Kategorien von Mustern gibt.
* zusätzliche Quellen für Muster, die sich auf ihre spezifische technische oder Anwendungsdomäne beziehen.

// end::DE[]

// tag::EN[]
[[LG-03-08]]

==== LG 03-08 [previously LG 2-5]: Describe, Explain and Apply Important Architectural Patterns (R1, R3)

Software architects can explain and provide examples for the following architectural patterns (R1):

* {glossary_url}layers[Layers]
* {glossary_url}pipes-and-filters[Pipes and Filters]
* {glossary_url}microservices[Microservices]

Software architects can explain several of the following architectural patterns,
explain their relevance for concrete systems, and provide examples. (R3)

* {glossary_url}blackboard[Blackboard]
* {glossary_url}broker[Broker]
* {glossary_url}cqrs[CQRS (Command-Query-Responsibility-Segregation)]
* {glossary_url}event-sourcing[Event sourcing]
* {glossary_url}dependency-injection[Dependency Injection] (see also <<LG-03-06>>)
* Integration and messaging patterns (e.g. from <<hohpe>>)
* {glossary_url}remote-procedure-call[Remote procedure call]
* {glossary_url}model-view-controller[MVC] (Model View Controller),
  {glossary_url}model-view-viewmodel[MVVM] (Model View ViewModel),
  {glossary_url}model-view-update[MVU] (Model View Update),
  {glossary_url}presentation-abstraction-control[PAC] (Presentation Abstraction Control)
* {glossary_url}plugin[Plugin]
* {glossary_url}ports-and-adapters[Ports and Adapters] (synonyms: Onion Architecture, Hexagonal Architecture, Clean Architecture)
* {glossary_url}service-oriented-architecture[SOA] (Service-Oriented Architecture)

Software architects know essential sources for architectural patterns, such as POSA (e.g. <<buschmanna>>) and PoEAA (<<fowler>>) (for information systems). (R3)

They know:

* that patterns are a way of achieving certain qualities for given problems and requirements within given contexts.
* that there are different categories of patterns.
* additional sources of patterns that relate to their specific technical or application domain.
// end::EN[]

===== {references}
<<buschmanna>>, <<buschmannb>>, <<eilebrecht>>, <<fowler>>, <<gof>>, <<hohpe>>, <<pethuru>>