
// tag::DE[]
[[LG-03-08]]
==== LZ 03-08 [ehemaliges LZ 2-05]: Wichtige Architekturmuster beschreiben, erklären und angemessen anwenden (R1, R3)

Softwarearchitekt:innen können die folgenden Architekturmuster erklären und Beispiele dafür liefern (R1):

* {glossary_url}layer[Layer]
* {glossary_url}pipes-and-filters[Pipes und Filter]
* {glossary_url}microservices[Microservices]

Softwarearchitekt:innen können einige der folgendene Muster erklären, ihre Relevanz für konkrete Systeme erläutern und Beispiele dafür liefern (R3):

* {glossary_url}blackboard[Blackboard]
* {glossary_url}broker[Broker]
* {glossary_url}cqrs[CQRS (Command-Query-Responsibility-Segregation)]
* {glossary_url}event-sourcing[Event sourcing]
* Integrations und Messaging-Patterns (z.B. aus <<hohpe>>)
* {glossary_url}model-view-controller[MVC] (Model View Controller),
  {glossary_url}model-view-viewmodel[MVVM] (Model View ViewModel),
  {glossary_url}model-view-update[MVU] (Model View Update),
  {glossary_url}presentation-abstraction-control[PAC] (Presentation Abstraction Control)
* {glossary_url}plugin[Plugin]
* {glossary_url}ports-and-adapters[Ports and Adapters] (Synonyme: Onion Architektur, Hexagonal Architektur, Clean Architektur)
* {glossary_url}service-oriented-architecture[SOA] (Service-Oriented Architektur)

Softwarearchitekt:innen kennen wesentliche Quellen für Architekturmuster, beispielsweise die POSA-Literatur (z.{nbsp}B. <<buschmanna>>) und PoEAA (<<fowler>>) (für Informationssysteme). (R3)

// end::DE[]

// tag::EN[]
[[LG-03-08]]

==== LG 03-08 [previously LG 2-05]: Describe, Explain and Apply Important Architectural Patterns (R1, R3)

Software architects can explain and provide examples for the following architectural patterns (R1):

* {glossary_url}layers[Layers]
* {glossary_url}pipes-and-filters[Pipes and Filters]
* {glossary_url}microservices[Microservices]

Software architects can explain several of the following architectural patterns,
explain their relevance for concrete systems, and provide examples. (R3)

* {glossary_url}blackboard[Blackboard]
* {glossary_url}broker[Broker]
* {glossary_url}cqrs[CQRS (Command-Query-Responsibility-Segregation)]
* {glossary_url}event-sourcing[Event sourcing]
* Integration and messaging patterns (e.g. from <<hohpe>>)
* {glossary_url}model-view-controller[MVC] (Model View Controller),
  {glossary_url}model-view-viewmodel[MVVM] (Model View ViewModel),
  {glossary_url}model-view-update[MVU] (Model View Update),
  {glossary_url}presentation-abstraction-control[PAC] (Presentation Abstraction Control)
* {glossary_url}plugin[Plugin]
* {glossary_url}ports-and-adapters[Ports and Adapters] (synonyms: Onion Architecture, Hexagonal Architecture, Clean Architecture)
* {glossary_url}service-oriented-architecture[SOA] (Service-Oriented Architecture)

Software architects know essential sources for architectural patterns, such as POSA (e.g. <<buschmanna>>) and PoEAA (<<fowler>>) (for information systems). (R3)

// end::EN[]
