
// tag::DE[]
[[LG-03-10]]
==== LZ 03-10 [ehemaliges LZ 2-04]: Querschnittsthemen identifizieren und Querschnittskonzepte entwerfen und umsetzen (R1)

Softwarearchitekt:innen können:

* die Bedeutung von {glossary_url}cross-cutting-concern[Querschnittsthemen] erklären
* solche Querschnittsthemen identifizieren
* Querschnittskonzepte entwerfen, unter anderem Persistenz, Kommunikation, GUI, Fehlerbehandlung, Nebenläufigkeit, Energieeffizienz
* mögliche wechselseitige Abhängigkeiten erkennen und beurteilen.

Softwarearchitekt:innen wissen, dass solche Querschnittskonzepte systemübergreifend wiederverwendbar sein können.

Siehe auch <<LG-04-07>>.
// end::DE[]

// tag::EN[]
[[LG-03-10]]
==== LG 03-10 [previously LG 2-04]: Identify, Design and Implement Cross-Cutting Concerns (R1)

Software architects are able to:

* explain the significance of {glossary_url}cross-cutting-concern[cross-cutting concerns]
* identify cross-cutting concerns
* design cross-cutting concepts, for example persistence, communication, GUI, error handling, concurrency, energy efficiency
* identify and assess potential interdependencies.

Software architects know that such cross-cutting concepts may be re-used across systems.

See also <<LG-04-07>>.

// end::EN[]

===== {references}
<<starke>>, <<starkelorz>>
