
// tag::DE[]
[[LG-03-08]]
==== LZ 03-08: Wichtige Muster beschreiben, erklären und angemessen anwenden (R1, R3)

Softwarearchitekt:innen können die folgenden Muster erklären und Beispiele dafür liefern (R1):

* {glossary_url}layer[Schichten (Layers)]
* {glossary_url}pipes-and-filters[Pipes und Filter]
* {glossary_url}microservices[Microservices]

Softwarearchitekt:innen können einige der folgenden Muster erklären, ihre Relevanz für konkrete Systeme erläutern und Beispiele dafür liefern (R3):

* {glossary_url}combinator[Combinator]
* Schnittstellenmuster wie {glossary_url}adapter[Adapter], {glossary_url}facade[Facade],
  und {glossary_url}proxy[Proxy].
  Architekt:innen sollten wissen, dass diese Muster unabhängig von bestimmten
  Programmiersprachen oder Frameworks verwendet werden können.
* {glossary_url}interpreter[Interpreter]
* {glossary_url}observer[Observer]
* {glossary_url}template-method[Template Method] und {glossary_url}strategy[Strategy]
* {glossary_url}visitor[Visitor]
* {glossary_url}blackboard[Blackboard]
* {glossary_url}broker[Broker]
* {glossary_url}cqrs[CQRS (Command-Query-Responsibility-Segregation)]
* {glossary_url}event-sourcing[Event sourcing]
* {glossary_url}dependency-injection[Dependency Injection] (siehe auch <<LG-03-06>>)
* Integrations und Messaging-Patterns (z.B. aus <<hohpe>>)
* {glossary_url}remote-procedure-call[Remote procedure call]
* {glossary_url}model-view-controller[MVC] (Model View Controller),
  {glossary_url}model-view-viewmodel[MVVM] (Model View ViewModel),
  {glossary_url}model-view-update[MVU] (Model View Update),
  {glossary_url}presentation-abstraction-control[PAC] (Presentation Abstraction Control)
* {glossary_url}plugin[Plugin]
* {glossary_url}ports-and-adapters[Ports and Adapters] (Synonyme: Onion Architektur, Hexagonal Architektur, Clean Architektur)
* {glossary_url}service-oriented-architecture[SOA] (Service-Oriented Architektur)

Softwarearchitekt:innen kennen wesentliche Quellen für Muster, beispielsweise <<gof,GOF>> die POSA-Literatur (z.{nbsp}B. <<buschmanna>>) und PoEAA (<<fowler>>) (für Informationssysteme). (R3)


Sie wissen:

* dass Muster ein Weg sind, bestimmte Qualitäten für gegebene Probleme und Anforderungen innerhalb gegebener Kontexte zu erreichen.
* zusätzliche Quellen für Muster, die sich auf ihre spezifische technische oder Anwendungsdomäne beziehen.

// end::DE[]

// tag::EN[]
[[LG-03-08]]

==== LG 03-08: Describe, Explain and Apply Important Patterns (R1, R3)

Software architects can explain and provide examples for the following patterns (R1):

* {glossary_url}layer[Layers]
* {glossary_url}pipes-and-filters[Pipes and Filters]
* {glossary_url}microservice[Microservices]

Software architects can explain several of the following patterns,
explain their relevance for concrete systems, and provide examples. (R3)

* {glossary_url}combinator[Combinator]
* Interfacing patterns like {glossary_url}adapter[Adapter], {glossary_url}facade[Facade],
  and {glossary_url}proxy[Proxy].
  Architects should know that these patterns can be used
  independently of a particular programming language or framework.
* {glossary_url}interpreter[Interpreter]
* {glossary_url}observer[Observer]
* {glossary_url}template-method[Template Method] and {glossary_url}strategy[Strategy]
* {glossary_url}visitor[Visitor]
* {glossary_url}blackboard[Blackboard]
* {glossary_url}broker[Broker]
* {glossary_url}cqrs[CQRS (Command-Query-Responsibility-Segregation)]
* {glossary_url}event-sourcing[Event sourcing]
* {glossary_url}dependency-injection[Dependency Injection] (see also <<LG-03-06>>)
* Integration and messaging patterns (e.g. from <<hohpe>>)
* {glossary_url}remote-procedure-call[Remote procedure call]
* {glossary_url}model-view-controller[MVC] (Model View Controller),
  {glossary_url}model-view-viewmodel[MVVM] (Model View ViewModel),
  {glossary_url}model-view-update[MVU] (Model View Update),
  {glossary_url}presentation-abstraction-control[PAC] (Presentation Abstraction Control)
* {glossary_url}plugin[Plugin]
* {glossary_url}ports-and-adapters[Ports and Adapters] (synonyms: Onion Architecture, Hexagonal Architecture, Clean Architecture)
* {glossary_url}service-oriented-architecture[SOA] (Service-Oriented Architecture)

Software architects know essential sources for patterns, such as <<gof,GOF>>, POSA (e.g. <<buschmanna>>) and PoEAA (<<fowler>>) (for information systems). (R3)

They know:

* that patterns are a way of achieving certain qualities for given problems and requirements within given contexts.
* additional sources of patterns that relate to their specific technical or application domain.
// end::EN[]

===== {references}
<<buschmanna>>, <<buschmannb>>, <<eilebrecht>>, <<fowler>>, <<gof>>, <<hohpe>>, <<pethuru>>
