
// tag::DE[]
[[LG-03-02]]
==== LZ 03-02 [ehemaliges LZ 2-2]: Softwarearchitekturen entwerfen (R1)

Softwarearchitekt:innen können:

* Softwarearchitekturen auf Basis bekannter funktionaler und Qualitätsanforderungen für nicht sicherheits- oder unternehmenskritische Softwaresysteme entwerfen und angemessen kommunizieren und dokumentieren
* Strukturentscheidungen hinsichtlich Systemzerlegung und Bausteinstruktur treffen, dabei Abhängigkeiten zwischen Bausteinen festlegen (siehe <<LG-03-06>>)
* gegenseitige Abhängigkeiten und Abwägungen bezüglich {glossary_url}architectural-decision[Architekturentscheidungen] erkennen und begründen
* Begriffe {glossary_url}blackbox[Blackbox] und {glossary_url}whitebox[Whitebox] erklären und zielgerichtet anwenden
* schrittweise Verfeinerung und Spezifikation von Bausteinen durchführen
* Architektursichten entwerfen, insbesondere Baustein-, Laufzeit- und Verteilungssicht (siehe <<LG-04-05>>)
* die aus Entscheidungen resultierenden Konsequenzen auf den Quellcode erklären
* domänenspezifische und technische Bestandteile in Architekturen trennen und diese Trennung begründen
* Risiken von Architekturentscheidungen identifizieren.

// end::DE[]

// tag::EN[]
[[LG-03-02]]
==== LG 03-02 [previously LG 2-2]: Design Software Architectures (R1)

Software architects are able to:

* design and appropriately communicate and document software architectures based upon known functional and quality requirements for software systems that are neither safety- nor business-critical
* make structural decisions regarding system decomposition and building-block structure, thereby defining dependencies between building blocks (see <<LG-03-06>>)
* recognize and justify interdependencies and trade-offs between {glossary_url}architectural-decision[architecture decisions];
* explain the terms {glossary_url}blackbox[black box] and {glossary_url}whitebox[white box] and apply them purposefully
* apply stepwise refinement and specification of building blocks
* design architecture views, especially building-block view, runtime view and deployment view (see <<LG-04-05>>)
* explain the consequences of decisions on the corresponding source code
* separate technical and domain-related elements of architectures and justify these decisions
* identify risks related to architecture decisions.

// end::EN[]

===== {references}
<<kruchten95>>, <<rozanskiwoods>>, <<starkelorz>>, <<arc42>>, <<brownc4>>, <<starke>>