// tag::DE[]

[[LZ-03-04]]
==== LZ 03-04 [ehemaliges LZ 2-06]: Entwurfsprinzipien erläutern und anwenden (R1-R3)

Softwarearchitekt:innen sind in der Lage zu erklären, was Entwurfsprinzipien sind.
Sie können deren grundlegende Ziele und deren Anwendung im Hinblick auf Softwarearchitektur skizzieren. (R2)

Softwarearchitekt:innen sind in der Lage:

* die unten aufgeführten Gestaltungsprinzipien zu erläutern und mit Beispielen zu illustrieren
* zu erklären, wie diese Prinzipien angewendet werden sollen
* darzulegen, wie Anforderungen die Anwendung dieser Prinzipien beeinflussen
* die Auswirkungen der Entwurfsprinzipien auf die Implementierung zu erläutern
* Quellcode und Architektur zu analysieren, um zu beurteilen, ob diese Entwurfsprinzipien angewendet wurden oder angewendet werden sollten


**Abstraktion** (R2)

* im Sinne eines Vorgehens zur Erarbeitung zweckmäßiger Generalisierungen
* als eine Entwurfstechnik, bei dem die Bausteine von Abstraktionen und nicht von Implementierungen abhängen
* Schnittstellen als Abstraktionen


**Modularisierung** (R1)

* Geheimnisprinzip (Information Hiding) und Kapselung (R1)
* Trennung von Verantwortlichkeiten (Separation of Concerns - SoC) (R1)
* Lose, aber funktionell ausreichende Kopplung (R1) von Bausteinen
//, siehe <<LZ-2-7, Lernziel 2-7>>
* Hohe Kohäsion (R1)
* Offen/geschlossen-Prinzip (R1)
* Liskov'sches Substitutionsprinzip (R3) als eine Möglichkeit, Konsistenz und konzeptionelle Integrität beim objektorientierten Design zu erreichen
* Dependency-Inversion-Prinzip (R1) - Umkehrung von Abhängigkeiten durch Schnittstellen oder ähnlichen Abstraktionen

**Konzeptionelle Integrität** (R2)

* bedeutet Einheitlichkeit (Homogenität, Konsistenz) von Lösungen für ähnliche Probleme zu erreichen (R2)
* als ein Mittel, um das Prinzip der geringsten Überraschung zu erreichen (principle of least surprise) (R3)

**Reduktion von Komplexität** (R3)

* als Motiv der Prinzipien KISS, YAGNI und CUPID <<north-cupid>>

**Erwarte Fehler** (R2-R3)

* als Mittel für den Entwurf robuster und widerstandsfähiger Systeme (R3)
* als eine Verallgemeinerung des Robustheitsgrundsatzes (_Postel's law_) (R2)
// end::DE[]

// tag::EN[]

[[LG-03-04]]
==== LG 03-04 [previously LG 2-06]: Explain and Use Design Principles (R1-R3)

Software architects are able to explain what design principles are.
They can outline their general objectives and applications with regard to software architecture. (R2)

Software architects are able to:

* explain the design principles listed below and can illustrate them with examples
* explain how those principles are to be applied
* explain how the requirements determine which principles should be applied
* explain the impact of design principles on the implementation
* analyze source code and architecture designs to evaluate whether these design principles have been applied or should be applied

**Abstraction** (R2)

* in the sense of a means for deriving useful generalizations
* as a design technique, where building blocks are dependent on the abstractions rather than depending on implementations
* interfaces as abstractions

**Modularization** (R1-R3)

* information hiding and encapsulation (R1)
* separation of concerns - SoC (R1)
* loose, but functionally sufficient, coupling (R1) of building blocks
//, refer to <<LG-2-7, LG 2-7>>
* high cohesion (R1)
* Open/closed principle (R1)
* Liskov substitution principle (R3) as a way to achieve consistency and conceptual integrity in OO design
* Dependency inversion principle (R1) by means of interfaces or similar abstractions

**Conceptual integrity** (R2)

* meaning uniformity (homogeneity, consistency) of solutions for similar problems (R2)
* as a means to achieve the principle of least surprise (R3)

**Complexity reduction** (R3)

* as the driving factor behind KISS, YAGNI, and CUPID <<north-cupid>>

**Expect errors** (R2-R3)

* as a means to design for robust and resilient systems (R3)
* as a generalization of the robustness principle (_Postel's law_) (R2)
// end::EN[]
