
// tag::DE[]
[[LZ-03-09]]
==== LZ 03-09 [ehemaliges LZ 2-04]: Querschnittsthemen entwerfen und umsetzen (R1)

Softwarearchitekt:innen können:

* die Bedeutung von Querschnittsthemen erklären
* Querschnittsthemen entscheiden und entwerfen, unter anderem Persistenz, Kommunikation, GUI, Fehlerbehandlung, Nebenläufigkeit, Energieeffizienz
* mögliche wechselseitige Abhängigkeiten dieser Entscheidungen erkennen und beurteilen.

Softwarearchitekt:innen wissen, dass solche Querschnittsthemen systemübergreifend wiederverwendbar sein können.

// end::DE[]

// tag::EN[]
[[LG-03-09]]
==== LG 03-09 [previously LG 2-04]: Design and Implement Cross-Cutting Concerns (R1)

Software architects are able to:

* explain the significance of such cross-cutting concerns
* decide on and design cross-cutting concerns, for example persistence, communication, GUI, error handling, concurrency, energy efficiency
* identify and assess potential interdependencies between these decisions.

Software architects know that such cross-cutting concerns may be re-used throughout the system.

// end::EN[]
