
// tag::DE[]

[[LZ-03-01]]
==== LZ 03-01 [ehemaliges LZ 2-08]: Qualitätsanforderungen mit passenden Ansätzen und Techniken erreichen (R1)

Softwarearchitekt:innen kennen und berücksichtigen den starken Einfluss von Qualitätsanforderungen in Architektur- und Entwurfsentscheidungen, beispielsweise für:

* Effizienz, Laufzeitperformance
* Verfügbarkeit
* Wartbarkeit, Modifizierbarkeit, Erweiterbarkeit, Adaptierbarkeit
* Energieeffizienz

Sie können:

* Lösungsmöglichkeiten, _Architectural Tactics_, angemessene Praktiken sowie technische Möglichkeiten zur Erreichung wichtiger Qualitätsanforderungen von Softwaresystemen (unterschiedlich für eingebettete Systeme bzw. Informationssysteme) erklären und anwenden
* mögliche Wechselwirkungen zwischen solchen Lösungsmöglichkeiten sowie die entsprechenden Risiken identifizieren und kommunizieren.

// end::DE[]

// tag::EN[]

[[LG-03-01]]
==== LG 03-01 [previously LG 2-08]: Achieve Quality Requirements with Appropriate Approaches and Techniques (R1)

Software architects understand and consider the considerable influence of quality requirements in architecture and design decisions, e.g. for:

* efficiency, runtime performance
* availability
* maintainability, modifiability, extensibility, adaptability
* energy efficiency

They can:

* explain and apply solution options, _Architectural Tactics_, suitable practices as well as technical possibilities to achieve important quality requirements of software systems (different for embedded systems or information systems)
* identify and communicate possible trade-offs between such solutions and their associated risks


// end::EN[]
