
// tag::DE[]
[[LZ-03-10]]
==== LZ 03-10 [ehemaliges LZ 2-04]: Querschnittsthemen identifizieren und Querschnittskonzepte entwerfen und umsetzen (R1)

Softwarearchitekt:innen können:

* die Bedeutung von Querschnittsthemen (synonym: Belange, Anliegen) erklären
* solche Querschnittsthemen identifizieren
* Querschnittskonzepte entwerfen, unter anderem Persistenz, Kommunikation, GUI, Fehlerbehandlung, Nebenläufigkeit, Energieeffizienz
* mögliche wechselseitige Abhängigkeiten erkennen und beurteilen.

Softwarearchitekt:innen wissen, dass solche Querschnittskonzepte systemübergreifend wiederverwendbar sein können.

// end::DE[]

// tag::EN[]
[[LG-03-10]]
==== LG 03-10 [previously LG 2-04]: Identify, Design and Implement Cross-Cutting Concerns (R1)

Software architects are able to:

* explain the significance of such cross-cutting concerns
* identify such cross-cutting concerns
* design cross-cutting concepts, for example persistence, communication, GUI, error handling, concurrency, energy efficiency
* identify and assess potential interdependencies.

Software architects know that such cross-cutting concerns may be re-used across systems.

// end::EN[]
