
// tag::DE[]
== Anforderungen und Randbedingungen

|===
| Dauer: 60 Min. | Übungszeit: 60 Min.
|===

=== Zielsetzung
Dieser Abschnitt vertieft das Verständnis der Teilnehmenden für Stakeholder-Anliegen, Anforderungen und Qualitäten von Softwaresystemen.
Sie lernen, den Einfluss von Stakeholdern auf Architekturentscheidungen zu erkennen sowie Konflikte und Synergien im Kontext von Entwicklungsprojekten einzuschätzen.
Durch die Auseinandersetzung mit verschiedenen Anforderungen und Einschränkungen erhalten sie einen Einblick in die effektive Berücksichtigung der Bedürfnisse der Stakeholder und der Projektvorgaben.
Weiterhin erkennen sie die Bedeutung von Qualitäten eines Softwaresystems als entscheidende Faktoren für den Architekturentwurf. 
Sie können solche Anforderungen mit Hilfe von Szenarien formulieren.

=== Wesentliche Begriffe
Qualität; Qualitätsmerkmale; DIN/ISO 25010; Q42; Qualitätsszenarien; Kompromisse/Wechselwirkungen von Qualitätseigenschaften; Anforderungen; Randbedingungen; Stakeholder-Anliegen


// end::DE[]

// tag::EN[]
== Requirements and Constraints

|===
| Duration: 60 min. | Exercises: 60 min.
|===

=== Purpose
This section deepens participants' understanding of stakeholder concerns, requirements, and system qualities in software architecture.
Participants learn to identify stakeholders and their influence on architectural decisions, discerning conflicts and synergies in the context of development projects.
By exploring diverse requirements and constraints, they gain insight into effectively addressing stakeholders' needs and project constraints.
Additionally, they recognize the significance of software system qualities as drivers for architectural design. 
They can formulate such requirements using scenarios.

=== Relevant Terms
Quality; quality characteristics (also called quality attributes); DIN/ISO 25010; Q42; quality scenarios; tradeoffs and interactions between quality characteristics; requirements; constraints; stakeholder concerns

// end::EN[]
