
// tag::DE[]
== Anforderungen und Randbedingungen

|===
| Dauer: 60 Min. | Übungszeit: 60 Min.
|===

=== Zielstellung
Dieser Abschnitt vertieft das Verständnis der Teilnehmenden für Stakeholder-Anliegen, Anforderungen und Qualitäten von Softwaresystemen.
Sie lernen, den Einfluss von Stakeholdern auf Architekturentscheidungen zu erkennen sowie Konflikte und Synergien im Projektkontext einzuschätzen.
Durch die Auseinandersetzung mit verschiedenen Anforderungen und Einschränkungen erhalten sie einen Einblick in die effektive Berücksichtigung der Bedürfnisse der Stakeholder und der Projektvorgaben.
Gleichzeitig erkennen sie die Bedeutung von Qualitäten eines Softwaresystems als entscheidende Faktoren für den Architekturentwurf. 

=== Wesentliche Begriffe
Qualität; Qualitätsmerkmale; DIN/ISO 25010; Qualitätsszenarien; Qualitätsbaum; Kompromisse/Wechselwirkungen von Qualitätseigenschaften; qualitative Architekturanalyse; Metriken und quantitative Analyse


// end::DE[]

// tag::EN[]
== Requirements and Constraints

|===
| Duration: 60 min. | Exercises: 60 min.
|===

=== Purpose
This section deepens participants' understanding of stakeholder concerns, requirements, and system qualities in software architecture.
Participants learn to identify stakeholders and their influence on architectural decisions, discerning conflicts and synergies within project contexts.
By exploring diverse requirements and constraints, they gain insight into effectively addressing stakeholders' needs and project constraints.
Additionally, they recognize the significance of software system qualities as drivers for architectural design. 

=== Relevant Terms
Quality; quality characteristics (also called quality attributes); DIN/ISO 25010; quality scenarios; quality tree; trade-offs between quality characteristics; qualitative architecture analysis; metrics and quantitative analysis

// end::EN[]
