
// tag::DE[]
[[LG-02-01]]
==== LZ 02-01: Stakeholder-Anliegen verstehen (R1-R3)

Architekten können Stakeholder und deren Anliegen sowie deren Auswirkungen auf die Softwarearchitektur oder den Entwurfs- und Entwicklungsprozess identifizieren. (R2)

Beispiele für Stakeholder und ihre Anliegen (R3):

|===
|Interessengruppe |Anliegen der Interessengruppe

| Produktmanagement
| z.{nbsp}B. benötigte Zeit für die Umsetzung der Anforderungen

| Projektmanagement
| z. B. benötigte Zeit und Budget für die Umsetzung, verbundene Risiken des
gewählten architekturellen Ansatzes

| Requirements Engineering, Fachbereiche
| z. B. Erfüllung der Anforderungen

| Entwicklungsteam
| z. B. zu implementierende Komponenten und Schnittstellen, Protokolle,
technologische Einschränkungen

| Qualitätssicherung und Test
| z. B. isoliertes Testen von Komponenten

| Betrieb
| z.{nbsp}B. Infrastrukturanforderungen im Zusammenhang mit dem Betrieb des Systems

|===

Softwarearchitekt:innen können potenzielle Konflikte zwischen kurz- und langfristigen Zielen erklären, um mögliche Konflikte (z.B., Geschäfts- und Projektziele vs. Architektur- und Wartbarkeitsziele) zu lösen. (R2)

Architekt:innen verstehen, dass nicht alle Anliegen der Stakeholder in Anforderungen umgesetzt werden können oder werden, aber dennoch berücksichtigt werden müssen. (R3)

Architekt:innen können die Anliegen der Stakeholder nutzen, um fehlende oder widersprüchliche Anforderungen zu entdecken und/oder Anforderungen und Einschränkungen an der Architektur zu validieren, z.B. in Stakeholder-Interviews. (R3)
// end::DE[]

// tag::EN[]
[[LG-02-01]]
==== LG 02-01: Understand Stakeholder Concerns (R1-R3)

Architects can identify stakeholders and their concerns, as well as their impact on the software architecture or the design and development process. (R2)

Examples of stakeholders and concerns (R3):

|===
|Stakeholder |Stakeholder Concern

| product management and product owners
| e.g., required time for the implementation of the requirements

| project managers
| e.g., required time and budget for the implementation, associated risks of the chosen architectural approach

| requirement engineers
| e.g., fulfillment of the requirements

| developers
| e.g., components and interfaces to be implemented, protocols, technology constraints

| quality assurance and testers
| e.g., isolated testing of components

| operations
| e.g., infrastructure requirements related to operating the system

|===

Software architects can explain potential conflicts between short-term and long-term goals, in order to resolve potential conflicts (e.g., business and project goals vs. architecture and maintainability goals). (R2)

Architects understand that not all stakeholder concerns can or will be translated into requirements, but may nevertheless need to be considered. (R3)

Architects can use stakeholder concerns to discover missing or conflicting requirements and/or validate requirements and constraints on the architecture, e.g., in stakeholder interviews. (R3)

// end::EN[]
