
// tag::DE[]
[[LG-02-02]]
==== LZ 02-02 [ehemaliges LZ 2-3]: Anforderungen und Randbedingungen klären und berücksichtigen können (R1-R3)

Softwarearchitekt:innen verstehen, dass sowohl Anforderungen als auch Randbedingungen Auswirkungen auf die Architektur und die Architekturarbeit haben können (R2).
Sie sind in der Lage, Anforderungen und Randbedingungen zu klären und beim Architekturentwurf und im Entwicklungsprozess zu berücksichtigen.
Sie wissen, dass ihre Entscheidungen zu zusätzlichen Anforderungen führen können.


Sie erkennen und berücksichtigen den Einfluss von:

* produktbezogenen Anforderungen wie (R1)
** funktionale Anforderungen
** {glossary_url}quality-requirement[Qualitätsanforderungen]

* Technologische Randbedingungen wie 
** bestehende oder geplante Hardware- und Software-Infrastruktur (R1)
** technologische Beschränkungen für Datenstrukturen und Schnittstellen (R2)
** Referenzarchitekturen, Bibliotheken, Komponenten und Frameworks (R1)
** Programmiersprachen (R2)

* Organisatorischen Randbedingungen wie
** Organisationsstruktur von Entwicklungsteams und Auftraggebenden (R1), insbesondere das Gesetz von Conway (R2)
** Unternehmens- und Teamkultur (R3)
** Partnerschaften und Kooperationen (R2)
** Normen, Richtlinien und Prozessmodelle (z.{nbsp}B. Genehmigungs- und Freigabeprozesse) (R2)
** Verfügbarkeit von Ressourcen wie Budget, Zeit und Personal (R1)
** Verfügbarkeit, Qualifikation und Engagement von Mitarbeitenden (R1)

* Regulatorischen Randbedingungen wie (R2)
** lokale und internationale rechtliche Einschränkungen
** Vertrags- und Haftungsfragen
** Datenschutzgesetze und Gesetze zum Schutz der Privatsphäre
** Fragen der Einhaltung oder Verpflichtungen zur Beweislast

* Trends wie (R3)
** Markttrends
** Technologietrends (z.{nbsp}B. Cloud, Microservices, Container, generative KI oder LLMs)
** Methodik-Trends (z.{nbsp}B. Agilität)

Softwarearchitekt:innen können beschreiben, wie diese Einflüsse auf Architekturentscheidungen wirken, und sie können die Konsequenzen einer Änderung der Einflussfaktoren anhand von Beispielen erläutern (R2).


// end::DE[]

// tag::EN[]
[[LG-02-02]]
==== LG 02-02 [previously LG 2-3]: Clarify and Consider Requirements and Constraints (R1-R3)

Software architects understand that both requirements and constraints can have an impact on the architecture and the architecture work (R2).
They are able to clarify requirements and constraints and take them into account in the architectural design and development process.
They know that their decisions can lead to additional requirements.

They should recognize and account for the impact of:

* product-related requirements such as (R1)
** functional requirements
** {glossary_url}quality-requirement[quality requirements]

* technological constraints such as 
** existing or planned hardware and software infrastructure (R1)
** technological constraints on data structures and interfaces (R2)
** reference architectures, libraries, components, and frameworks (R1)
** programming languages (R2)

* organizational constraints such as
** organizational structure of the development team and of the customer (R1), in particular Conway's law (R2).
** company and team cultures (R3)
** partnerships and cooperation agreements (R2)
** standards, guidelines, and process models (e.g. approval and release processes) (R2)
** available resources like budget, time, and staff (R1)
** availability, skill set, and commitment of staff (R1)

* regulatory constraints such as (R2)
** local and international legal constraints
** contract and liability issues
** data protection and privacy laws
** compliance issues or obligations to provide burden of proof

* trends such as (R3)
** market trends
** technology trends (e.g. cloud, microservices, container, generative AI or LLMs))
** methodology trends (e.g. Agile)

Software architects are able to describe how those factors can influence architecture decisions and can elaborate on the consequences of changing influencing factors by providing examples for some of them (R2).

// end::EN[]
