
// tag::DE[]
[[LG-02-03]]
==== LZ 02-03 [ehemaliges LZ 4-1]: Qualitäten eines Softwaresystems verstehen und erklären (R1)

Softwarearchitekt:innen wissen dass der Begriff "Qualität" in verschiedenen Kontexten unterschiedlich benutzt wird: 

* im Kontext von Qualitätsmanagement im Sinne von "Güte" und 
* im Sinne spezifischer Eigenschaften (eines Softwaresystems). 

In diesem Lernziel geht es um letzteres.

Softwarearchitekt:innen können erklären dass:

* es unterschiedliche Taxonomien gibt, die Qualitäten von Softwaresystemen kategorisieren 
* manche Kategorisierungen zwischen Funktionalität und Qualität unterscheiden, wie zum Beispiel IREB <<IREBFoundation>>
* Softwarearchitekt:innen die Qualitäten eines Softwaresystems beeinflussen können
* die Veränderung einer Qualität andere so beeinflussen kann, dass Abwägungen notwendig werden, wie z.{nbsp}B.
** Konfigurierbarkeit versus Zuverlässigkeit
** Speicherbedarf versus Leistungseffizienz
** Sicherheit versus Benutzbarkeit
** Laufzeitflexibilität versus Wartbarkeit.


Sie verstehen, dass sich eine einzelne Anforderung auf mehrere Qualitäten beziehen kann.
// end::DE[]


// tag::EN[]
[[LG-02-03]]
==== LG 02-03 [previously LG 4-1]: Understand and Explain Qualities of a Software System (R1)

Software architects know that the term "quality" is used differently in different contexts:

* referring to "excellence" in the context of quality management, and
* referring to a "specific property (of a software system)" in others.

This learning goal refers to the latter.

Software architects can explain that:

* several taxonomies categorizing qualities of software systems exist
* some categorizations distinguish between functionality and quality, e.g. IREB <<IREBFoundation>>
* software architecture can impact a software system's qualities,
* impacting one quality can impact others, necessitating trade-offs, such as:
** configurability versus reliability
** memory requirements versus performance efficiency
** security versus usability
** runtime flexibility versus maintainability.

They understand that a single requirement might pertain to several qualities.
// end::EN[]

===== {references}

<<IREBFoundation>>, <<iso25010>>, <<bass>>, <<q42>>