// tag::FEEDBACK[]
:filename: 02-design/01-design-duration-terms.adoc
include::../config/_feedback.adoc[]
// end::FEEDBACK[]

// tag::DE[]

== Entwurf und Entwicklung von Softwarearchitekturen

|===
| Dauer: 330 Min. | Übungszeit: 90 Min.
|===


=== Wesentliche Begriffe

Entwurf; Vorgehen beim Entwurf; Entwurfsentscheidung; Sichten; Schnittstellen; technische Konzepte und Querschnittskonzepte; Stereotypen; Architekturmuster; Entwurfsmuster; Mustersprachen; Entwurfsprinzipien; Abhängigkeit; Kopplung; Kohäsion; fachliche und technische Architekturen; Top-down- und Bottom-Up-Vorgehen; modellbasierter Entwurf; iterativer/inkrementeller Entwurf; Domain-Driven Design

// end::DE[]

// tag::EN[]
== Design and development of software architectures

|===
| Duration: 330 min. | Excercises: 90 min.
|===

=== Relevant terms
Design; design approach; design decision; views; interfaces; technical and cross-cutting concerns; stereotypes; architectural patterns; pattern languages; design principles; dependencies; coupling; cohesion; functional and technical architectures; top-down and bottom-up approaches; model-based design; iterative/incremental design; domain-driven design

// end::EN[]

// tag::REMARK[]
// end::REMARK[]
