// tag::FEEDBACK[]
:filename: 02-design/01-design-duration-terms.adoc
include::../config/_feedback.adoc[]
// end::FEEDBACK[]

// tag::DE[]

== Entwurf und Entwicklung von Softwarearchitekturen

|===
| Dauer: 300 Min. | Übungszeit: 90 Min.
|===


=== Wesentliche Begriffe

Entwurf, Vorgehen beim Entwurf, Entwurfsentscheidung, Sichten, Schnittstellen, technische und querschnittliche Konzepte, Stereotypen, Architekturmuster, Entwurfsmuster, Mustersprachen, Entwurfsprinzipien, Abhängigkeit, Kopplung, Kohäsion, fachliche und technische Architekturen, Top-down- und Bottom-Up-Vorgehen, modellbasierter Entwurf, iterativer/inkrementeller Entwurf, Domain-Driven Design

// end::DE[]

// tag::EN[]
== Design and development of software architectures

|===
| Duration: 300 min. | Excercises: 90 min.
|===

=== Terms and concepts
Design; design approach; design decision; views, technical and crosscutting concerns; architectural patterns; design principles; domain-related and technical architectures; model-based design; iterative/incremental design; domain-driven design; top-down and bottom-up approaches

// end::EN[]

// tag::REMARK[]
// end::REMARK[]
