// tag::FEEDBACK[]
:filename: 02-design/LZ-2-07.adoc
include::../config/_feedback.adoc[]
// end::FEEDBACK[]

// tag::DE[]

[[LZ-2-7]]
==== LZ 2-7: Abhängigkeiten von Bausteinen planen (R1)

Softwarearchitekten verstehen Abhängigkeiten und Kopplung zwischen Bausteinen und können diese gezielt einsetzen:

* sie kennen unterschiedliche Arten der Abhängigkeiten von Bausteinen (beispielsweise strukturelle Kopplung über Benutzung/Delegation, Schachtelung, Besitz, Erzeugung, Vererbung, zeitliche Kopplung, Kopplung über Datentypen oder über Hardware);
* sie können solche Arten der Kopplung gezielt einsetzen und die Konsequenzen solcher Abhängigkeiten einschätzen;
* Sie kennen Möglichkeiten zur Auflösung bzw. Reduktion von Kopplung und können diese anwenden, beispielsweise:
** Muster (siehe <<LZ-2-5,Lernziel 2-5>>)
** Grundlegende Entwurfsprinzipien (siehe <<LZ-2-6,Lernziel 2-6>>)


// end::DE[]

// tag::EN[]

[IMPORTANT]
====
Translation missing!
====

// end::EN[]

// tag::REMARK[]
// end::REMARK[]


ifdef::withRemarks[]
[NOTE]
====
GS/CL: sprachlich leicht umformuliert, einige Muster entfernt, jetzt komplett R1.
====
endif::withRemarks[]
