// tag::FEEDBACK[]
:filename: 02-design/LZ-2-08.adoc
include::../config/_feedback.adoc[]
// end::FEEDBACK[]

// tag::DE[]

[[LZ-2-8]]
==== LZ 2-8: Qualitätsziele mit passenden Ansätzen und Techniken erreichen (R1)

Softwarearchitekten können Taktiken, angemessene Praktiken sowie technische Möglichkeiten zur Erreichung wichtiger Qualitätsziele von Softwaresystemen (unterschiedlich für eingebettete Systeme bzw. Informationssysteme) erklären und anwenden, beispielsweise für:

* Effizienz/Performance
* Wartbarkeit, Modifizierbarkeit, Erweiterbarkeit, Adaptierbarkeit

Sie können entsprechende Risiken identifizieren.

// end::DE[]

// tag::EN[]

[[LG-2-8]]
==== LG 2-8: Achieve quality requirements with appropriate approaches and techniques (R1)

Software architects can explain and apply tactics, appropriate practices and technical possibilities to achieve important quality requirements of software systems (different for embedded systems or information systems), e.g. for:

* efficiency/performance
* maintainability, modifiability, extensibility, adaptability

They can identify corresponding risks.

// end::EN[]

// tag::REMARK[]

[NOTE]
====
GS: Proposal: upgrade to R1

GS: Feb 2019: Ich bin der Meinung, dass dieses LZ ins Kapitel 2 (statt bisher 5) des Lehrplanes gehört, und habe es zum neuen LZ 2-8 gemacht
====
// end::REMARK[]
