// tag::DE[]

[[LZ-2-6]]
==== LZ 2-6: Entwurfsprinzipien erläutern und anwenden (R1)
Softwarearchitekt:innen können die folgenden Entwurfsprinzipien erläutern und anwenden:

* Abstraktion
* Modularisierung, unter Berücksichtigung von:
** Geheimnisprinzip (_Information Hiding_) und Kapselung
** Trennung von Verantwortlichkeiten (_Separation of Concerns_)
** Hoher Kohäsion
* Single-Responsibility-Prinzip
* Offen-Geschlossen-Prinzip (_Open-/Closed-Principle_)
* möglichst lose, aber funktional ausreichende Kopplung der Bausteine (siehe auch <<LZ-2-7,LZ 2-7>>)
* Umkehrung von Abhängigkeiten durch Schnittstellen oder ähnliche Abstraktionen (_Dependency Inversion_) 
* konzeptioneller Integrität zur Erreichung der Gleichförmigkeit (Homogenität, Konsistenz) von Lösungen für ähnliche Probleme (R2)

Softwarearchitekt:innen verstehen die Einflüsse der Entwurfsprinzipien auf Quellcode und können diese gezielt einsetzen.

// end::DE[]

// tag::EN[]

[[LG-2-6]]
==== LG 2-6: Explain and use design principles (R1)
Software architects are able to explain and apply the following design principles:

* Abstraction
* Modularization, with regard to:
** information hiding and encapsulation
** separation of concerns
** high cohesion
* Single-Responsibility
* Open/closed principle
* Loose, but functionally sufficient coupling of building blocks (cf. <<LG-2-7, LG 2-7>>)
* Dependency inversion by means of interfaces or similar abstractions
* Conceptual integrity to achieve uniformity (homogeneity, consistency) of solutions for similar problems (R2)

Software architects understand the impact of design principles onto source code and are able to apply these appropriately.


// end::EN[]

// tag::REMARK[]
[NOTE]
====
* GS, May 2019: moved _dependency injection_ to LG-02-07 
* GS, Feb. 2019: fixed wrong indentation for modularization (SRP and OCP are principles on their own).
Added links to leaning goals. Adjusted intro sentence of EN version.
* CL/GS, Jan 2019: Minor rephrasing (DE version)
====
// end::REMARK[]
