// tag::FEEDBACK[]
:filename: 02-design/LZ-2-09.adoc
include::../config/_feedback.adoc[]
// end::FEEDBACK[]

// tag::DE[]

[[LZ-2-9]]
==== LZ 2-9: Schnittstellen entwerfen und festlegen (R1-R3)

Softwarearchitekten kennen die hohe Bedeutung von Schnittstellen. Sie können Schnittstellen zwischen Architekturbausteinen sowie externe Schnittstellen zwischen dem System und Elementen außerhalb des Systems entwerfen bzw. festlegen.

Sie kennen:

* wünschenswerte Eigenschaften von Schnittstellen und können diese beim Entwurf einsetzen:
** einfach zu erlernen, einfach zu benutzen, einfach zu erweitern;
** schwer zu missbrauchen;
** funktional vollständig aus Sicht der Nutzer oder nutzender Bausteine.
* die Notwendigkeit unterschiedlicher Behandlung interner und externer Schnittstellen.
* unterschiedliche Implementierungsansätze von Schnittstellen (R3):
** ressourcenorientierter Ansatz (wie in REpresentational State Transfer)
** serviceorientierter Ansatz (wie bei WS-*/SOAP-basierten Webservices)

// end::DE[]

// tag::EN[]
[[LG-2-9]]
==== LG 2-9: Design and define interfaces (R1-R3)

Software architects know about the importance of interfaces. They are able to design or specify interfaces between architectural building blocks as well as external interfaces between the system and elements outside of the system.

They know: 

* desired characteristics of interfaces and can use them in the design:
** easy to learn, easy to use, easy to extend;
** hard to misuse;
** functionally complete from the perspective of users or building blocks using them.
* the necessity to treat internal and external interfaces differently.
* different approaches for implementing interfaces (R3):
** Resource-oriented approach (see Representational State Transfer);
** Service-oriented approach (see WS-*/SOAP-based web services.

// end::EN[]

// tag::REMARK[]

[NOTE]
====
GS (June 2019): re-ordered sub-goals to have R1 before R3.

GS (Feb 2019): Added the differentiation between external and internal interfaces.

GS/CL (Jan 2019): Nachsatz zu Dokumentation entfernt, der gehört in Kapitel 3
====
// end::REMARK[]
