// tag::FEEDBACK[]
:filename: 02-design/LZ-2-05.adoc
include::../config/_feedback.adoc[]
// end::FEEDBACK[]

// tag::DE[]

==== LZ 2 5: Wichtige Architekturmuster und Architekturstile beschreiben, erklären und angemessen anwenden (R1-R3)

Softwarearchitekten kennen diverse Architekturmuster und können diese bedarfsgerecht einsetzen:

* Schichten, Layer (R1)
* Pipes und Filter (R1)
* Client/Server (R1)
* Blackboard (R2)
* Model-View-Controller und Varianten (R2)
* Broker (R2)
* Remote Procedure Call (R2)
* Messaging (R2), z.B. mit Events und Commands
* Adapter und Facade (R1)
* Proxy (R1)
* Plugin (R1)


Softwarearchitekten kennen wesentliche Quellen für Architekturmuster, beispielsweise die POSA-Literatur und PoEAA (für Informationssysteme) (R3)

// end::DE[]

// tag::EN[]
==== LZ 2 5: Describe, explain and appropriately apply important architectural patterns and styles (R1-R3)

Software architects know various architectural patterns and can use them as required:

* Layers, layers (R1)
* Pipes and filters (R1)
* Client/Server (R1)
* Blackboard (R2)
* Model View Controller and Variants (R2)
* Broker (R2)
* Remote Procedure Call (R2)
* Messaging (R2), e.g. with events and commands
* Adapter and Facade (R1)
* Proxy (R1)
* Plugin (R1)


Software architects know essential sources for architectural patterns, such as POSA literature and PoEAA (for information systems) (R3).

// end::EN[]

// tag::REMARK[]

[NOTE]
====
GS/CL: significantly shortenend, removed "styles" -> followed RRs' suggestion below.

RR: I’ve seen people differentiate between architecture styles and patterns. I don’t think the difference is important enough to differentiate. I do make a difference between architecture patterns and design patterns, but it’s not always clear if a pattern is an architecture pattern, a design pattern, or both.

I suggest using “architecture-level design patterns” or simply “architecture and design patterns”. – or simply “architecture pattern” / “Architekturmuster”
====
// end::REMARK[]
