
// tag::DE[]
[[LZ-2-5]]
==== LZ 2-5: Wichtige Lösungsmuster beschreiben, erklären und angemessen anwenden (R1, R3)


Softwarearchitekt:innen kennen verschiedene Architekturmuster (siehe unten) und können sie gegebenenfalls anwenden.

Sie wissen (R3):

* dass Muster ein Weg sind, bestimmte Qualitäten für gegebene Probleme und Anforderungen innerhalb gegebener Kontexte zu erreichen
* dass es verschiedene Kategorien von Mustern gibt
* zusätzliche Quellen für Muster, die sich auf ihre spezifische technische oder Anwendungsdomäne beziehen


Softwarearchitekt:innen können die folgenden Muster erklären und Beispiele dafür liefern (R1):

* Schicht (Layers):
** Abstraktionsschichten (Abstraction layers) verbergen Details, Beispiel: ISO/OSI-Netzwerkschichten oder "Hardware-Abstraktionsschicht". Siehe <https://en.wikipedia.org/wiki/Hardware_abstraction>.
** Eine andere Interpretation sind Schichten zur (physischen) Trennung von Funktionalität oder Verantwortung, siehe <https://en.wikipedia.org/wiki/Multitier_architecture>.

* Pipes-and-Filter: Repräsentativ für Datenflussmuster, die die schrittweise Verarbeitung in eine Reihe von Verarbeitungsaktivitäten ("Filter") und zugehörige Transport/Puffer ("Pipes") separieren.
* Microservices teilen Anwendungen in separate ausführbare Diensteauf, die über Netzwerk (remote) kommunizieren.
* Dependency Injection als eine mögliche Lösung für das Dependency-Inversion-Prinzip


Softwarearchitekt:innen können einige der folgendene Muster erklären, ihre Relevanz für konkrete Systeme erläutern und Beispiele dafür liefern (R3):

* Blackboard: Behandlung von Problemen, die nicht durch deterministische Algorithmen lösbar sind, sondern vielfältiges Wissen erfordern.
* Broker: verantwortlich für die Koordination der Kommunikation zwischen Anbieter(n) und Verbraucher(n), angewandt in verteilten Systemen. Verantwortlich für die Weiterleitung von Anfragen und/oder die Übermittlung von Ergebnissen, Fehlern und Ausnahmen.
* Kombinator (Synonym: Closure of Operations), für Domänenobjekte vom Typ T, suchen Sie nach Operationen sowohl mit Input- als auch Output-Typ T. Siehe <<yorgey>>
* CQRS (Command-Query-Responsibility-Segregation): Trennung von Lese- und Schreibvorgängen in Informationssystemen. Erfordert Einblicke in konkrete Datenbank-/Persistenztechnologie, um die unterschiedlichen Eigenschaften und Anforderungen von "Lese-" und "Schreib"-Operationen zu verstehen.
* Event-Sourcing: Behandlung von Datenoperationen durch eine Abfolge von Ereignissen (Events), von denen jedes in einem Append-only Speicher aufgezeichnet wird.
* Interpreter: repräsentieren Domänenobjekt oder DSL als Syntax, bieten eine Funktion, die eine semantische Interpretation des Domänenobjekts getrennt vom Domänenobjekt selbst implementiert.
* Integrations- oder Messaging-Patterns (z.B. aus Hohpe+2004])
* Die MVC-, MVVM-, MV-Update-, PAC-Musterfamilie, die die externe Repräsentation (Ansicht) von Daten von Operationen Diensten und deren Koordination trennt .
* Schnittstellenmuster wie Adapter, Fassade, Proxy. Solche Muster helfen bei der Integration von Subsystemen und/oder bei der Vereinfachung von Abhängigkeiten. Architekt:innen sollten wissen, dass diese Muster unabhängig von (Objekt-)Technologie verwendet werden können.
** Adapter: Entkopplung von Konsument und Provider - wenn die Schnittstelle des Providers nicht genau mit der des Konsumenten übereinstimmt.
** Fassade: vereinfacht die Verwendung eines Providers für den/die Consumer durch vereinfachten Zugriff.
** Proxy: Ein Vermittler/Stellvertreter zwischen Consumer und Provider, der beispielsweise die zeitliche Entkopplung, das Caching von Ergebnissen oder die Zugriffkontrolle auf den Provider ermöglicht.
* Observer (Beobachter): ein Produzent von Werten benachrichtigt eine zentrale Vermittlungsstelle, bei der sich Interessenten (Consumer) registrieren können, um über Änderungen benachrichtigt zu werden.
* Plug-In: erweitert das Verhalten einer Komponente.
* Ports&Adapters (syn. Onion-Architecture, Hexagonale Architektur): konzentrieren die Domänenlogik im Zentrum des Systems, und besitzen lediglich an den Rändern Verbindungen zur Außenwelt (Datenbank, UI). Abhängigkeiten von aussen nach innen (Outside-In), niemals von innen nach aussen (Inside-Out).
* Remote Procedure Call: eine Funktion oder einen Algorithmus in einem anderen Adressraum ausführen lassen.
* SOA: Service-orientierte Architektur. Ein Ansatz zur Bereitstellung abstrakter Dienste statt konkreter Implementierungen für die Benutzer des Systems, um die Wiederverwendung von Diensten über Abteilungen und zwischen Unternehmen zu fördern.
* Template und Strategy: spezifische Algorithmen durch Kapselung flexibel machen.
* Visitor (Besucher): Traversierung von Datenstrukturen von spezifischer Verarbeitung trennen.


Softwarearchitekt:innen kennen wesentliche Quellen für Architekturmuster, beispielsweise die POSA-Literatur (z.B. <<buschmanna>>) und PoEAA (<<fowler>>) (für Informationssysteme) (R3)

// end::DE[]

// tag::EN[]
[[LG-2-5]]
==== LG 2-5: Describe, explain and appropriately apply important solution patterns (R1, R3)


Software architects know:

* various architectural patterns and can apply them when appropriate
* that patterns are a way to achieve certain qualities for given problems and requirements within given contexts
* that various categories of patterns exist (R3)
* additional sources for patterns related to their specific technical or application domain (R3)


Software architects can explain and provide examples for the following patterns (R1):

* Layers:
** Abstraction layers hide details, example: ISO/OSI network layers, or "hardware abstraction layer". See https://en.wikipedia.org/wiki/Hardware_abstraction
** Another interpretation are Layers to (physically) separate functionality or responsibility, see https://en.wikipedia.org/wiki/Multitier_architecture

* Pipes-and-Filter: Representative for data flow patterns, breaking down stepwise processing into a series of processing-activities ("Filter") and associated data transport/buffering capabilities ("Pipes").
* Microservices split application into separate executable that communicate via network
* Dependency Injection as a possible solution for the Dependency-Inversion-Principle


Software architects can explain several of the following patterns, explain their relevance for concrete systems, and provide examples. (R3)

* Blackboard: handle problems that cannot be solved by deterministic algorithms but require diverse knowledge
* Broker:  responsible for coordinating communication between provider(s) and consumer(s), applied in distributed systems. Responsible for forwarding requests and/or transmitting results and exceptions
* Combinator (synonym: closure of operations), for domain object of type T, look for operations with both input and output type T. See <<yorgey>>
* CQRS (Command-Query-Responsibility-Segregation): Separates read- from write concerns in information systems. Requires some context on database-/persistence technology to understand the different properties and requirements of "read" versus "write" operations
* Event-Sourcing:  handle operations on data by a sequence of events, each of which is recorded in an append-only store
* Interpreter: represent domain object or DSL as syntax, provide function implementing a semantic interpretation of domain object separately from domain object itself
* Integration and messaging patterns (e.g. from Hohpe+2004])
* The MVC, MVVM, MV-Update, PAC family of patterns, separating external representation (view) from data, services and their coordination
* Interfacing-patterns like Adapter, Facade, Proxy. Such patterns help in integration of subsystems and/or simplification of dependencies. Architects should know that these patterns can be used independent of (object) technology
** Adapter: decouple consumer and provider - where the interface of the provider does not exactly match that of the consumer. The Adapter decouples one party from interface-changes in the other
** Facade: simplifies usage of a provider for consumer(s) by providing simplified access
** Proxy: An intermediate between consumer and provider, enabling temporal decoupling, caching of results, controlling access to the provider etc.
* Observer: a producer of values over time notifies a central switchboards where consumers can register to be notified of them
* Plug-In: extend the behaviour of a component
* Ports&Adapters (syn. Onion-Architecture, Hexagonal-Architecture): concentrate domain logic in the center of the system, have connections to the outside world (database, UI) at the edges, dependencies only outside-in, never inside-out
* Remote Procedure Call: make a function or algorithm execute in a different address space
* SOA: Service-Oriented Architecture. An approach to provide abstract services rather than concrete implementations to users of the system to promote reuse of services across departments and between companies
* Template and Strategy: make specific algorithms flexible by encapsulating them
* Visitor: separate data-structure traversal from specific processing

Software architects know essential sources for architectural patterns, such as POSA (e.g. <<buschmanna>>) and PoEAA (<<fowler>>) (for information systems) (R3).

// end::EN[]

// tag::REMARK[]

[NOTE]
====
GS (August 2019): Added reference for PoEAA, replaced POSA by Buschmann-references
GS (Feb 2019): re-ordered to match priorities.

GS/CL (Jan 2019): significantly shortenend, removed "styles" -> followed RRs' suggestion below.

RR: I’ve seen people differentiate between architecture styles and patterns. I don’t think the difference is important enough to differentiate. I do make a difference between architecture patterns and design patterns, but it’s not always clear if a pattern is an architecture pattern, a design pattern, or both.

I suggest using “architecture-level design patterns” or simply “architecture and design patterns”. – or simply “architecture pattern” / “Architekturmuster”
====
// end::REMARK[]
