// tag::FEEDBACK[]
:filename: 02-design/LZ-2-04.adoc
include::../config/_feedback.adoc[]
// end::FEEDBACK[]

// tag::DE[]
[[LZ-2-4]]
==== LZ 2-4: Querschnittskonzepte entwerfen und umsetzen (R1)

Softwarearchitekten können:

* die Bedeutung von Querschnittskonzepten erklären
* Querschnittskonzepte entscheiden und entwerfen, beispielsweise Persistenz, Kommunikation, GUI, Fehlerbehandlung, Nebenläufigkeit
* mögliche wechselseitige Abhängigkeiten dieser Entscheidungen erkennen und beurteilen.

Softwarearchitekten wissen, dass solche Querschnittskonzepte systemübergreifend wiederverwendbar sein können.

// end::DE[]

// tag::EN[]
[[LG-2-4]]
==== LG 2-4: Design and implement cross-cutting concerns (R1)

Software architects are able to:

* explain the significance of such cross-cutting concerns
* decide on and design cross-cutting concerns, for example persistence, communication, GUI, error handling, concurrency
* identify and assess potential interdependencies between these decisions.

Software architects know that such cross-cutting concepts may be re-used throughout the system.

// end::EN[]

// tag::REMARK[]
[NOTE]
====
GS/CL: leicht umformuliert. Modified EN translation of "Konzept" to "concept" instead of "concern".
====
// end::REMARK[]
