// tag::DE[]

[[LZ-2-7]]
==== LZ 2-7: Abhängigkeiten von Bausteinen planen (R1)

Softwarearchitekt:innen verstehen Abhängigkeiten und Kopplung zwischen Bausteinen und können diese gezielt einsetzen. 
Sie:

* kennen unterschiedliche Arten der Abhängigkeiten von Bausteinen (beispielsweise strukturelle Kopplung über Benutzung/Delegation, Schachtelung, Besitz, Erzeugung, Vererbung, zeitliche Kopplung, Kopplung über Datentypen oder über Hardware)
* können solche Arten der Kopplung gezielt einsetzen und die Konsequenzen solcher Abhängigkeiten einschätzen
* kennen Möglichkeiten zur Auflösung bzw. Reduktion von Kopplung und können diese anwenden, beispielsweise:
** Muster (siehe <<LZ-2-5, LZ 2-5>>)
** Grundlegende Entwurfsprinzipien (siehe <<LZ-2-6, LZ 2-6>>)
** Externalisierung von Abhängigkeiten, d.h. konkrete Abhängigkeiten erst zur Installations- oder Laufzeit festlegen, etwa durch Anwendung von _Dependency Injection_.


// end::DE[]

// tag::EN[]
[[LG-2-7]]
==== LG 2-7: Planning dependencies between building blocks (R1)

Software architects understand dependencies and coupling between building blocks and can use them in a targeted manner. They:

* know different types of dependencies of building blocks (e.g. structural coupling via use/delegation, nesting, ownership, generation, inheritance, temporal coupling, coupling via data types or via hardware)
* can use such types of coupling in a targeted manner and can assess the consequences of such dependencies
* know and can apply possibilities to reduce or eliminate coupling, for example:
** Patterns (see <<LZ-2-5, LG 2-5>>)
** Fundamental design principles (see <<LZ-2-6, LG 2-6>>)
** Externalization of dependencies, i.e. defining concrete dependencies at installation- or runtime, for example by using _Dependency Injection_.

// end::EN[]

// tag::REMARK[]

[NOTE]
====
GS, Feb 2019: re-formated DE version, adjusted EN translation to modifications of DE version
====
// end::REMARK[]


ifdef::withRemarks[]
[NOTE]
====
* GS (May 2019): added depency injection (which was removed from LG-2-6)
* GS/CL (Feb 2019): sprachlich leicht umformuliert, einige Muster entfernt, jetzt komplett R1.
====
endif::withRemarks[]
