
// tag::DE[]
[[LZ-2-4]]
==== LZ 2-4: Querschnittskonzepte entwerfen und umsetzen (R1)

Softwarearchitekt:innen können:

* die Bedeutung von Querschnittskonzepten erklären
* Querschnittskonzepte entscheiden und entwerfen, beispielsweise Persistenz, Kommunikation, GUI, Fehlerbehandlung, Nebenläufigkeit, Energieeffizienz
* mögliche wechselseitige Abhängigkeiten dieser Entscheidungen erkennen und beurteilen.

Softwarearchitekt:innen wissen, dass solche Querschnittskonzepte systemübergreifend wiederverwendbar sein können.

// end::DE[]

// tag::EN[]
[[LG-2-4]]
==== LG 2-4: Design and implement cross-cutting concepts (R1)

Software architects are able to:

* explain the significance of such cross-cutting concepts
* decide on and design cross-cutting concepts, for example persistence, communication, GUI, error handling, concurrency, energy efficiency
* identify and assess potential interdependencies between these decisions.

Software architects know that such cross-cutting concepts may be re-used throughout the system.

// end::EN[]
