
// tag::DE[]
[[LZ-2-3]]
==== LZ 2-3: Einflussfaktoren auf Softwarearchitektur erheben und berücksichtigen können (R1-R2)

Softwarearchitekt:innen können Einflussfaktoren (Randbedingungen) als Einschränkungen der Entwurfsfreiheit erarbeiten und berücksichtigen.
Sie verstehen, dass ihre Entscheidungen weitere Anforderungen und Einschränkungen für das zu entwerfende System, seine Architektur oder den Entwicklungsprozess mit sich bringen können.

Sie erkennen und berücksichtigen den:

* Einfluss von Qualitätsanforderungen
* Einfluss technischer Entscheidungen und Konzepte
* (möglichen) Einfluss organisatorischer und juristischer Faktoren (R2)
* Einfluss verschiedener Stakeholder (R2)

// end::DE[]

// tag::EN[]
[[LG-2-3]]
==== LG 2-3: Identify and consider factors influencing software architecture (R1-R2)

Software architects are able to gather and consider constraints and influencing factors that restrict their decisions. 
They understand that their decisions may imply further requirements and constraints on the system being designed, its architecture, or the development process."

They should recognize and consider the:

* impact of quality requirements
* impact of technical decisions and concepts
* (potential) impact of organizational, legal, and other constraints (R2)
* impact of stakeholder concerns (R2)

// end::EN[]


// tag::REMARK[]

[NOTE]
====
GS (May 31st 2019): fixed punctuation, added R2 to last sentence in DE version
RR: Stakeholder sind neu.
====
// end::REMARK[]
