
// tag::DE[]
[[LZ-2-3]]
==== LZ 2-3: Anforderungen klären und berücksichtigen können (R1-R3)

Softwarearchitekt:innen können Anforderungen (inklusive Randbedingungen als Einschränkungen der Entwurfsfreiheit) klären und berücksichtigen.
Sie verstehen, dass ihre Entscheidungen zu weiteren Anforderungen (inklusive Randbedingungen) an das zu entwerfende System, seine Architektur oder den Entwicklungsprozess führen können. 

Sie erkennen und berücksichtigen den Einfluss von:

* funktionale Anforderungen (R1)

* Qualitätsanforderungen (R1)

* Technologische Randbedingungen wie 
** bestehende oder geplante Hardware- und Software-Infrastruktur (R1)
** technologische Beschränkungen für Datenstrukturen und Schnittstellen (R2)
** Referenzarchitekturen, Bibliotheken, Komponenten und Frameworks (R1)
** Programmiersprachen (R2)

* Organisatorischen Randbedingungen wie
** Organisationsstruktur von Entwicklungsteams und Auftraggebenden (R1), insbesondere das Gesetz von Conway (R2)
** Unternehmens- und Teamkultur (R3)
** Partnerschaften und Kooperationen (R2)
** Normen, Richtlinien und Prozessmodelle (z.B. Genehmigungs- und Freigabeprozesse) (R2)
** Verfügbarkeit von Ressourcen wie Budget, Zeit und Personal (R1)
** Verfügbarkeit, Qualifikation und Engagement von Mitarbeitenden (R1)

* Regulatorischen Randbedingungen wie
** lokale und internationale rechtliche Einschränkungen (R2)
** Vertrags- und Haftungsfragen (R2)
** Datenschutzgesetze und Gesetze zum Schutz der Privatsphäre (R2)
** Fragen der Einhaltung oder Verpflichtungen zur Beweislast (R2)

* Trends wie
** Markttrends (R3)
** Technologietrends (z.B. Blockchain, Microservices) (R3)
** Methodik-Trends (z.B. agil) (R3)
** (potenzielle) Auswirkungen weiterer Stakeholderinteressen und vorgegebener oder extern festgelegter Designentscheidungen (R3) 
// end::DE[]

// tag::EN[]
[[LG-2-3]]
==== LG 2-3: Identify and Consider Factors Influencing Software Architecture (R1-R3)


Software architects are able to clarify and consider requirements (including constraints that restrict their decisions).
They understand that their decisions can lead to additional requirements (including constraints) on the system being designed, its architecture, or the development process. 


They should recognize and account for the impact of:

* functional requirements (R1)

* quality requirements (R1)

* Technological constraints such as 
** existing or planned hardware and software infrastructure (R1)
** technological constraints on data structures and interfaces (R2)
** reference architectures, libraries, components, and frameworks (R1)
** programming languages (R2)

* Organizational constraints such as
** organizational structure of the development team and of the customer (R1), in particular Conway's law (R2).
** company and team cultures (R3)
** partnerships and cooperation agreements (R2)
** standards, guidelines, and process models (e.g. approval and release processes) (R2)
** available resources like budget, time, and staff (R1)
** availability, skill set, and commitment of staff (R1)

* Regulatory constraints such as
** local and international legal constraints (R2)
** contract and liability issues (R2)
** data protection​ and privacy laws (R2)
** compliance issues or obligations to provide burden of proof (R2)​

* Trends such as
** market trends (R3)
** technology trends (e.g. blockchain, microservices) (R3)
** methodology trends (e.g. agile) (R3)
** (potential) impact of further stakeholder concerns and mandated design decisions (R3)

Software architects are able to describe how those factors can influence design decisions and can elaborate on the consequences of changing influencing factors by providing examples for some of them (R2).

// end::EN[]
