==== LZ 2-2: Architekturen entwerfen (R1)

Softwarearchitekten können:

* Architekturen auf Basis bekannter funktionaler und Qualitätsanforderungen für nicht sicherheits- oder unternehmenskritische Softwaresysteme entwerfen und angemessen dokumentieren;
* gegenseitige Abhängigkeiten und Wechselwirkungen von Entwurfsentscheidungen erkennen und begründen;
* Strukturentscheidungen hinsichtlich Systemzerlegung und Bausteinstruktur treffen, dabei Abhängigkeiten zwischen Bausteinen festlegen;
* Blackbox- und Whitebox-Begriff erklären und zielgerichtet anwenden;
* schrittweise Verfeinerung und Spezifikation von Bausteinen durchführen;
* Architektursichten entwerfen, insbesondere Baustein-, Laufzeit- und Verteilungssicht;
* Abbildung der Architektur auf den Quellcode festlegen und die damit verbundenen Konsequenzen bewerten;
* fachliche und technische Bestandteile in Architekturen trennen und diese Trennung be-gründen;
* Risiken von Entwurfsentscheidungen identifizieren.


Softwarearchitekten kennen und berücksichtigen in Architektur- und Entwurfsentscheidungen:

* den starken Einfluss von Qualitätsanforderungen – wie beispielsweise Wartbarkeit, Verfügbarkeit, Effizient;
* Lösungsmöglichkeiten, „Design Tactics“, angemessene Praktinen sowie technische Möglichkeiten zur Erreichung wichtiger Qualitätsanforderungen;
* mögliche Wechselwirkungen zwischen solchen Lösungsmöglichkeiten.

ifdef::withRemarks[]
[NOTE]
====
GS/CL: DDD-Konstrukte entfernt

RR: Removed text relating to decisions. This is covered in LG 3-8
====
endif::withRemarks[]
