// tag::DE[]
[[LG-05-01]]
==== LZ 05-01: Gründe für Architekturanalyse kennen (R1)

Softwarearchitekt:innen verstehen, dass es verschiedene mögliche Gründe gibt, um eine Architekturanalyse durchzuführen, zum Beispiel:

* Risiken und mögliche Verbesserungen im Architekturentwurf  identifizieren (vor, während und nach der Implementierung)
* feststellen, ob der Architekturentwurf die Anforderungen erfüllt oder erfüllen wird
* erheben, inwiefern die Implementierung zu Architekturentscheidungen und Architekturentwurf passt
* überprüfen, inwiefern architekturrelevante Stakeholderanforderungen berücksichtigt sind

// end::DE[]

// tag::EN[]
[[LG-05-01]]
==== LG 05-01: Know Reasons for Architecture Analysis (R1)

Software architects understand that there are different possible reasons for performing architecture analysis, for example:

* identify risks and possible improvements in the architecture design (before, during, or after implementation)
* determine if the architecture design fulfills, or will fulfill, the requirements
* assess conformance of the implementation to the architecture decisions and design
* verify that architecturally relevant stakeholder concerns are addressed

// end::EN[]
