
<<<
// tag::DE[]
=== Abgrenzung
Dieser Lehrplan reflektiert den aus heutiger Sicht des iSAQB e.V. notwendigen und sinnvollen Inhalt zur Erreichung der Lernziele des CPSA-F. Er stellt keine vollständige Beschreibung des Wissensgebiets „Softwarearchitektur“ dar.

Folgende Themen oder Konzepte sind *nicht Bestandteil des CPSA-F*:

* konkrete Implementierungstechnologien, -frameworks oder -bibliotheken
* Programmierung oder Programmiersprachen
* Spezifische Vorgehensmodelle
* Grundlagen oder Notationen der Modellierung (wie etwa UML)
* Systemanalyse und Requirements Engineering (siehe dazu das Ausbildungs- und Zertifizierungsprogramm des IREB e. V., https://ireb.org, International Requirements Engineering Board)
* Test (siehe dazu das Ausbildungs- und Zertifizierungsprogramm des ISTQB e. V., https://istqb.org, International Software Testing Qualification Board)
* Projekt- oder Produktmanagement
* Einführung in spezifische Werkzeuge.

Ziel des Trainings ist es, die Grundlagen für den Erwerb der für den jeweiligen Einsatzfall notwendigen weiterführenden Kenntnisse und Fertigkeiten zu vermitteln.

// end::DE[]

// tag::EN[]
=== Out of Scope
This curriculum reflects the contents currently considered by the iSAQB members to be necessary and useful for achieving the learning goals of CPSA-F. It is not a comprehensive description of the entire domain of 'software architecture'.

The following topics or concepts are not part of CPSA-F:

* specific implementation technologies, frameworks or libraries
* programming or programming languages
* specific process models
* fundamentals of modelling notations (such as UML) or fundamentals of modelling itself
* system analysis and requirements engineering (please refer to the education and certification program by IREB e. V., https://ireb.org, International Requirements Engineering Board)
* software testing (please refer to the education and certification program by ISTQB e.V., https://istqb.org, International Software Testing Qualification Board)
* project or product management
* introduction to specific software tools.

 The aim of the training is to provide the basics for acquiring the advanced knowledge and skills required for the respective application.

// end::EN[]

