
// tag::DE[]
=== Voraussetzungen
Der iSAQB e. V. kann in Zertifizierungsprüfungen die hier genannten Voraussetzungen durch entsprechende Fragen prüfen.

Teilnehmende sollten die im Nachfolgenden genannten Kenntnisse und/oder Erfahrung mitbringen. Insbesondere bilden substanzielle praktischen Erfahrungen aus der Softwareentwicklung im Team eine wichtige Voraussetzung zum Verständnis des vermittelten Lernstoffes und für eine erfolgreiche Zertifizierung.

* mehr als 18 Monate praktische Erfahrung in arbeitsteiliger Softwareentwicklung (d.h. in Teams), erworben durch Programmierung unterschiedlicher Systeme außerhalb der Ausbildung
* Kenntnisse und praktische Erfahrung in mindestens einer höheren Programmiersprache, insbesondere:
** Konzepte der 
*** Modularisierung (Pakete, Namensräume)
*** Parameterübergabe (_Call-by-Value, Call-by-Reference_)
*** Gültigkeit (_scope_), beispielsweise von Typ- oder Variablendeklaration und -definition
** Grundlagen von Typsystemen (statische und dynamische Typisierung, generische Datentypen)
** Fehler- und Ausnahmebehandlung in Software
** Mögliche Probleme von globalem Zustand und globalen Variablen

* Grundlegende Kenntnisse von:
** Modellierung und Abstraktion
** Algorithmen und Datenstrukturen (etwa Listen, Bäume, HashTable, Dictionary/Map)
** UML (Klassen-, Paket-, Komponenten- und Sequenzdiagramme) und deren Bezug zum Quellcode
** Vorgehen beim Testen von Software (z.B. Unit- und Akzeptanztests)


Hilfreich für das Verständnis einiger Konzepte sind darüber hinaus:

* Grundbegriffe bzw. Unterschiede von imperativer, deklarativer, objektorientierter und funktionaler Programmierung
* praktische Erfahrung in 
** einer höheren Programmiersprache
** Konzeption und Implementierung verteilt ablaufender Anwendungen, wie etwa Client/Server-Systeme oder Web-Anwendungen
** technischer Dokumentation, insbesondere in der Dokumentation von Quellcode, Systementwürfen oder technischen Konzepten

// end::DE[]


// tag::EN[]
=== Prerequisites
The iSAQB e. V. may check the following prerequisites in certification examinations via corresponding questions.

Participants should have the following knowledge and/or experience. 
In particular, substantial practical experience from software development in a team is an important prerequisite for understanding the learning material and successful certification.

* More than 18 months of practical experience with software development, gained through team-based development of several systems outside of formal education
* Knowledge of and practical experience with at least one higher programming language, especially:
** Concepts of 
*** modularization (packages, namespaces, etc.)
*** parameter-passing (_call-by-value, call-by-reference_)
*** _scope_, i.e. of type- and variable declaration and definition
** Basics of type systems (static vs. dynamic typing, generic data types)
** Error- and exception handling in software
** Potential problems of global state and global variables

* Basic knowledge of:
** modelling and abstraction
** algorithms and data structures (i.e. Lists, Trees, HashTable, Dictionary, Map)
** UML (class, package, component and sequence diagrams) and their relation to source code
** approaches to testing of software (e.g. unit- and acceptance testing)


Furthermore, the following will be useful for understanding several concepts:

* Basics and differences of imperative, declarative, object-oriented and functional programming
* Practical experience in 
** a higher level programming language
** designing and implementing distributed applications, such as client-server systems or web applications
** technical documentation, especially documenting source code, system design or technical concepts

// end::EN[]


