// tag::DE[]
=== Struktur, Dauer, Didaktik

Die in den nachfolgenden Kapiteln des Lehrplans genannten Zeiten sind lediglich Empfehlungen.
Die Dauer einer Schulung sollte mindestens 3 Tage betragen, kann aber durchaus länger sein.
Anbieter können sich durch Dauer, Didaktik, Art und Aufbau der Übungen sowie der detaillierten Kursgliederung voneinander unterscheiden.
Insbesondere die Art (fachliche und technische Domänen) der Beispiele und Übungen können die jeweiligen Schulungsanbieter individuell festlegen.

[cols="<,>", options="header,footer"]
|===

| Inhalt | Empfohlene Dauer (min)

| 1. Grundlagen | 120

| 2. Anforderungen und Randbedingungen | 180

| 3. Entwurf und Entwicklung | 360

| 4. Beschreibung und Kommunikation | 240

| 5. Analyse und Bewertung | 90

| 6. Beispiele | 90

| Summe | 1080

|===

// end::DE[]

// tag::EN[]
=== Structure, Duration and Teaching Methods

Study times given in the following sections of the curriculum are just recommendations.
The duration of a training course should be at least three days, but may as well be longer.
Providers may vary in their approach to duration, teaching methods, the type and structure of exercises as well as the detailed course outline.
The types (domains and technologies) of examples and exercises can be determined individually by training providers.


[cols="<,>", options="header,footer"]
|===

| Content | Recommended Duration (min)

| 1. Basic Concepts of Software Architecture | 120

| 2. Requirements and Constraints | 180

| 3. Design and Development | 360

| 4. Specification and Communication | 240

| 5. Analysis and Assessment | 90

| 6. Examples | 90

| Total | 1080

|===
// end::EN[]

