// tag::DE[]
=== Struktur, Dauer, Didaktik und weitere Details lizenzierter Schulungen

Die in den nachfolgenden Kapitels des Lehrplans genannten Zeiten sind Empfehlungen.
Die Dauer einer Schulung sollte mindestens 3 Tage betragen, kann aber durchaus länger sein.
Anbieter können sich durch Dauer, Didaktik, Art und Aufbau der Übungen sowie der detaillierten Kursgliederung voneinander unterscheiden.
Insbesondere die Art (fachliche und technische Domänen) der Beispiele und Übungen kann der jeweilige Schulungsanbieter individuell festlegen.
// end::DE[]

// tag::EN[]
=== Structure, duration and teaching methods

Study times given in the following sections of the curriculum are recommendations.
The duration of a training course should be at least three days, but may as well be longer.
Providers may vary in their approach to duration, teaching methods, the type and structure of exercises as well as the detailed course outline.
The types (domains and technologies) of examples and exercises can be determined individually by the training provider.
// end::EN[]

// tag::REMARK[]
// end::REMARK[]
