
// tag::DE[]
=== Lernziele und Prüfungsrelevanz
Die Kapitel des Lehrplans sind anhand von priorisierten Lernzielen gegliedert.
Die Prüfungsrelevanz dieser Lernziele beziehungsweise deren Unterpunkte ist beim jeweiligen Lernziel ausdrücklich gekennzeichnet (durch Angabe der Kennzeichen R1, R2 oder R3, siehe nachstehende Tabelle).

Jedes Lernziel beschreibt die zu vermittelnden Inhalte inklusive ihrer Kernbegriffe und -konzepte. Bezüglich der Prüfungsrelevanz verwendet der Lehrplan folgende Kategorien:

[cols="1,2,6,2",options="header"]
|===
| ID 
| Lernziel-Kategorie 
| Bedeutung 
| Relevanz für Prüfung

| R1
| Können
| Diese Inhalte sollen die Teilnehmenden nach der Schulung selbstständig anwenden können. Innerhalb der Schulung werden diese Inhalte durch Übungen und Diskussionen abgedeckt.
| Inhalte *werden* geprüft.

| R2
| Verstehen
| Diese Inhalte sollen die Teilnehmenden grundsätzlich verstehen. Sie werden in Schulungen i. d. R. nicht durch Übungen vertieft.
| Inhalte *können* geprüft werden.

| R3
| Kennen
| Diese Inhalte (Begriffe, Konzepte, Methoden, Praktiken oder Ähnliches) können das Verständnis unterstützen oder das Thema motivieren. Sie werden in Schulungen bei Bedarf thematisiert.
| Inhalte *werden nicht* geprüft.
|===

Bei Bedarf enthalten die Lernziele Verweise auf weiterführende Literatur, Standards oder andere Quellen.
Die Abschnitte "Begriffe und Konzepte" zu Beginn jedes Kapitels zeigen Worte, die mit dem Inhalt des Kapitels in Verbindung stehen und z. T. auch in den Lernzielen verwendet werden.

// end::DE[]

// tag::EN[]
=== Learning Goals and Relevance for the Examination
The structure of the curriculum's chapters follows a set of prioritized learning goals.
For each learning goal, relevance for the examination of this learning goal or its sub-elements is clearly stated (by the R1, R2, R3 classification, see the table below).
Every learning goal describes the contents to be taught including their key terms and concepts.

Regarding relevance for the examination, the following categories are used in this curriculum:


[cols="1,2,6,2",options="header"]
|===
| ID
| Learning-goal category
| Meaning
| Relevance for examination

| R1
| Being able to 
| These are the contents participants will be expected to be able to put into practice independently upon completion of the course. Within the course, these contents will be covered through exercises and discussions.
| Contents *will be* part of the examination.

| R2
| Understanding 
| These are the contents participants are expected to understand in principle.
They will normally not be the primary focus of exercises in training.
| Contents *may be* part of the examination.

| R3
| Knowing 
| These contents (terms, concepts, methods, practices or similar) can enhance understanding and motivate the topic.
They may be covered in training if required.
| Contents will *not be* part of examination.
|===

If required, the learning goals include references to further reading, standards or other sources.
The sections "Terms and Concepts" of each chapter list words that are associated with the contents of the chapter.
Some of them are used in the descriptions of learning goals.

// end::EN[]
