// tag::DE[]
=== Lernziele und Prüfungsrelevanz
Die Kapitel des Lehrplans sind anhand von priorisierten Lernzielen gegliedert.
Die Prüfungsrelevanz dieser Lernziele beziehungsweise deren Unterpunkte ist beim jeweiligen Lernziel ausdrücklich ge-kennzeichnet (durch Angabe der Kennzeichen R-1, R-2 oder R-3, siehe Tabelle).

Jedes Lernziel beschreibt die zu vermittelnden Inhalte inklusive ihrer Kernbegriffe und -konzepte. Bezüglich der Prüfungsrelevanz verwendet der Lehrplan folgende Kategorien:

[cols="1,1,6",options="header"]
|===
| Lernziel-Kategorie | Kenn-zeichen | Relevanz für Prüfung

| Können
| R1
| Diese Inhalte sollen die Teilnehmer nach der Schulung selbständig anwenden können. Innerhalb der Schulung werden diese Inhalte durch Übungen und Diskussionen abgedeckt.	*Inhalte werden geprüft*.
| Verstehen
|	R2
| Diese Inhalte sollen die Teilnehmer grundsätzlich verstehen. Sie werden in Schulungen i. d. R. nicht durch Übungen vertieft.	*Inhalte können geprüft werden.*
| Kennen
| R3
| Diese Inhalte (Begriffe, Konzepte, Methoden, Praktiken oder Ähnliches) können das Verständnis unterstützen oder das Thema motivieren. Sie werden in Schulungen bei Bedarf thematisiert. |Inhalte *werden nicht geprüft*.
|===

Bei Bedarf enthalten die Lernziele Verweise auf weiterführende Literatur, Standards oder andere Quellen.
Die Abschnitte "Begriffe und Konzepte" zu Beginn jedes Kapitels zeigen Worte, die mit dem Inhalt des Kapitels in Verbindung stehen und z. T. auch in den Lernzielen verwendet werden.
Der iSAQB e. V. kann in Zertifizierungsprüfungen die oben genannten Voraussetzungen durch entsprechende Fragen prüfen. 
// end::DE[]

// tag::EN[]
// end::EN[]

// tag::REMARK[]
// end::REMARK[]
