
// tag::DE[]
[[LZ-4-3]]
==== LZ 4-3: Softwarearchitekturen qualitativ analysieren (R2-R3)
Softwarearchitekt:innen:

* kennen methodische Vorgehensweisen zur qualitativen Analyse von Softwarearchitekturen (R2), beispielsweise nach ATAM (R3)
* können kleinere Systeme qualitativ analysieren (R2)
* wissen, dass zur qualitativen Analyse und Bewertung von Architekturen folgende Informationsquellen helfen können (R2):
** Qualitätsanforderungen, beispielsweise in Form von Qualitätsbäumen und -szenarien
** Architekturdokumentation
** Architektur- und Entwurfsmodelle
** Quellcode
** Metriken
** Sonstige Dokumentationen des Systems, etwa Anforderungs-, Betriebs- oder Testdokumentation.

// end::DE[]

// tag::EN[]
[[LG-4-3]]
==== LG 4-3: Qualitative analysis of software architectures (R2-R3)
Software architects:

* know methodical approaches for the qualitative analysis of software architectures (R2), for example, as specified by ATAM (R3);
* can qualitatively analyze smaller systems (R2)
* know that the following sources of information can help in the qualitative analysis of architectures (R2):
** quality requirements, e.g. in the form of quality trees and scenarios
** architecture documentation
** architecture and design models
** source code
** metrics
** other documentation of the system, such as requirements, operational or test documentation.

// end::EN[]
