
// tag::DE[]
[[LZ-4-2]]
==== LZ 4-2: Qualitätsanforderungen an Softwarearchitekturen klären (R1)

Softwarearchitekt:innen können:

* architekturrelevante Qualitätsanforderungen mit den Verantwortlichen klären, z. B. bzgl. deren Verständlichkeit, Machbarkeit, Widersprüche usw.
* die Stakeholder bei der Definition bzw. Verbesserung der Qualitätsanforderungen, -szenarien und -bäumen unterstützen
* Qualitätsanforderungen, -szenarien und -bäume als Basis für Architekturentscheidungen verwenden.

// end::DE[]

// tag::EN[]
[[LG-4-2]]
==== LG 4-2: Clarify quality requirements for software architectures (R1)

Software architects can:

* clarify architecturally relevant quality requirements with those responsible, e.g. regarding their understandability, feasibility, contradictions, etc.
* support stakeholders with the definition or improvement of the quality requirements, quality scenarios, and quality trees
* use quality requirements, quality scenarios, and quality trees as a basis for architecture decisions.

// end::EN[]
