// tag::DE[]
[[LZ-4-4]]
==== LZ 4-4: Softwarearchitekturen quantitativ bewerten (R2)

Softwarearchitekten kennen Ansätze zur quantitativen Analyse und Bewertung (Messung) von Software.

Sie wissen, dass:

* quantitative Bewertung helfen kann, kritische Teile innerhalb von Systemen zu identifizieren
* zur Bewertung von Architekturen weitere Informationen hilfreich sein können, etwa:
** Anforderungs- und Architekturdokumentation
** Quellcode und diesbezügliche Metriken wie Lines-of-Code, (zyklomatische) Komplexität, ein- und ausgehende Abhängigkeiten
** bekannte Fehler in Quellcode, insbesondere Fehlercluster
** Testfälle und Testergebnisse.

// end::DE[]

// tag::EN[]
[[LG-4-4]]
==== LG 4-4: Quantitative evaluation of software architectures (R2)

Software architects know approaches for the quantitative analysis and evaluation (measurement) of software.

They know that:

* quantitative evaluation can help to identify critical parts within systems
* further information can be helpful for the evaluation of architectures, for example:
** Requirements and architecture documentation
** source code and related metrics such as lines of code, (cyclomatic) complexity, inbound and outbound dependencies
** known errors in source code, especially error clusters
** Test cases and test results.

// end::EN[]

// tag::REMARK[]
[NOTE]
====
GS: see https://github.com/isaqb-org/curriculum-foundation/issues/16[issue 16]
====
// end::REMARK[]
