// tag::FEEDBACK[]
:filename: 04-quality/LZ-4-2.adoc
include::../config/_feedback.adoc[]
// end::FEEDBACK[]

// tag::DE[]
[[LZ-4-2]]
==== LZ 4-2: Qualitätsanforderungen an Softwarearchitekturen klären (R1)

Softwarearchitekten können:

* spezifische Qualitätsanforderungen an die zu entwickelnde Software und deren Architekturen klären und konkret formulieren, beispielsweise in Form von Szenarien und Qualitätsbäumen;
* Szenarien und Qualitätsbäume erklären und anwenden;

// end::DE[]

// tag::EN[]
[[LG-4-2]]
==== LG 4-2: Clarify quality requirements for software architectures (R1)

Software architects can:

* clarify and formulate specific quality requirements for the software to be developed and its architectures, for example in the form of scenarios and quality trees;
* Explain and apply scenarios and quality trees;

// end::EN[]

// tag::REMARK[]
[NOTE]
====
RR: (March 2019) We don’t (shouldn’t) define (formulieren) quality requirements. This is the customer’s job. We shouldn’t define how fast, secure, etc. a system should be. See https://github.com/isaqb-org/curriculum-foundation/issues/15[issue 15]
====
// end::REMARK[]
