
== Grundbegriffe

|===
| Dauer: 120 Min. | Übungszeit: keine
|===


=== Wesentliche Begriffe
Softwarearchitektur, Architekturdomänen, Struktur, Bausteine/Komponenten, Schnittstellen, Bezie-hungen, Querschnittskonzepte, Nutzen von Softwarearchitektur, Softwarearchitekten und deren Verantwortlichkeiten, Rolle, Aufgaben und benötigte Fähigkeiten, Stakeholder und deren Anlie-gen, funktionale Anforderungen, Qualitätsanforderungen, Randbedingungen, Einflussfaktoren, Typen von IT-Systemen (eingebettete Systeme, Echtzeitsysteme, Informationssysteme etc.)

=== Lernziele

==== LZ 1-1: Definitionen von Softwarearchitektur diskutieren (R1)
Vergleich mehrerer Definitionen von Softwarearchitektur (u. a. ISO 42010/IEEE 1471, SEI, Booch etc.) und deren Gemeinsamkeiten benennen:

*	Komponenten/Bausteine mit Schnittstellen und Beziehungen
*	Bausteine als allgemeiner Begriff, Komponenten als eine spezielle Ausprägung davon
*	Strukturen, Querschnittskonzepte, Prinzipien
*	Architekturentscheidungen mit systemweiten oder den gesamten Lebenszyklus betreffenden Konsequenzen

==== LZ 1-2: Nutzen von Softwarearchitektur verstehen und herausstellen (R1)

*	Das Ziel von Softwarearchitektur ist die Erreichung der Qualitätsanforderungen wie Zuverlässigkeit, Wartbarkeit, Änderbarkeit, Sicherheit als Differenzierung im Gegensatz zur Implementierung der Funktionalität
*	Softwarearchitektur unterstützt die Erstellung und Wartung von Software, insbesondere die Implementierung
*	Softwarearchitektur unterstützt das Verständnis über das System, bezogen auf sämtlichen relevanten Stakeholder

==== LZ 1-3: Softwarearchitektur in Software-Lebenszyklus einordnen (R2)

* Einordnung von Softwarearchitektur in die gesamte Entwicklung von IT-Systemen

*	Zusammenhang mit Geschäfts- und Betriebsprozessen für
** Informationssysteme
** Entscheidungsunterstützungssysteme (Data Warehouse, Management Information Systems)
*	Das Management von Änderungen von Anforderungen, Technologien oder der Systemumgebung im Bezug auf die Softwarearchitektur.

==== LZ 1-4: Aufgaben und Verantwortung von Softwarearchitekten verstehen (R1)
Softwarearchitekten tragen die Verantwortung für die Erreichung der geforderten oder notwendigen Qualität und Funktionalität der Lösung. Sie müssen diese Verantwortung, abhängig vom jeweiligen Prozess- oder Vorgehensmodell, mit der Gesamtverantwortung der Projektleitung oder anderen Rollen koordinieren.

Aufgaben und Verantwortung von Softwarearchitekten:

*	Anforderungen und Randbedingungen klären, hinterfragen und bei Bedarf verfeinern. Hierzu zählen neben den funktionalen Anforderungen (Required Features) insbesondere die geforderten Qualitätsmerkmale (_Required Constraints_)
*	Strukturentscheidungen hinsichtlich Systemzerlegung und Bausteinstruktur treffen, dabei Abhängigkeiten und Schnittstellen zwischen den Bausteinen festlegen
*	Querschnittskonzepte entscheiden (beispielsweise Persistenz, Kommunikation, GUI) und bei Bedarf umsetzen
*	Softwarearchitektur auf Basis von Sichten, Architekturmustern sowie technischen und querschnittlichen Konzepten kommunizieren und dokumentieren
*	Umsetzung und Implementierung der Architektur begleiten, Rückmeldungen der beteiligten Stakeholder bei Bedarf in die Architektur einarbeiten, Konsistenz von Quellcode und Softwarearchitektur prüfen und sicherstellen
*	Softwarearchitektur bewerten, insbesondere hinsichtlich Risiken bezüglich der geforderten Qualitätsmerkmale
*	Die Konsequenzen von Architekturentscheidungen erkennen, aufzeigen und gegenüber anderen Stakeholdern argumentieren

Sie sollen selbständig die Notwendigkeit von Iterationen bei allen Aufgaben erkennen und Möglichkeiten für entsprechende Rückmeldung aufzeigen

==== LZ 1-5: Rolle von Softwarearchitekten in Beziehung zu anderen Stakeholdern setzen (R1)
Softwarearchitekten können ihre Rolle erklären und ihren Beitrag zur Systementwicklung in Verbindung mit anderen Stakeholdern kontextspezifisch ausgestalten, insbesondere zu:

*	Anforderungsanalyse (Systemanalyse, Anforderungsmanagement, Fachbereich)
*	Implementierung
*	Projektleitung und -management
*	Produktmanagement, Product-Owner
*	Qualitätssicherung
*	IT-Betrieb (Produktion, Rechenzentren), zutreffend primär für Informationssysteme
*	Hardwareentwicklung
*	Unternehmens- oder Enterprisearchitektur, Architekturboard

==== LZ 1-6: Zusammenhang zwischen Entwicklungsvorgehen und Softwarearchitektur erläutern (R1)

*	Softwarearchitekten können den Einfluss von iterativem Vorgehen auf Architekturentscheidungen erläutern (hinsichtlich Risiken und Prognostizierbarkeit);
*	Softwarearchitekten müssen aufgrund inhärenter Unsicherheit oftmals iterativ arbeiten und entscheiden. Dabei müssen sie bei anderen Stakeholdern systematisch Rückmeldung einholen.

==== LZ 1-7: Architektur- und Projektziele differenzieren (R1)
Systeme können im Rahmen von Projekten entwickelt werden, aber auch im Rahmen von Scrum-Sprints, Iterationen, Releases oder andere Vorgehensweisen. Der Begriff „Projekt“ im Titel des Lernzieles bezieht sich auf jede dieser möglichen Formen der Arbeitsorganisation.

*	Softwarearchitekten können auf Basis bestehender Anforderungen Architekturziele identifizieren und präzisieren;
* 	sie können (langfristige) Architekturziele sowie deren Abgrenzung gegen (kurzfristige) Projektziele erklären.


==== LZ 1-8: Explizite von impliziten Aussagen unterscheiden (R1)

*	Softwarearchitekten können Annahmen oder Voraussetzungen explizit darstellen und vermeiden implizite Annahmen;
*	sie wissen, dass implizite Annahmen potentielle Missverständnisse zwischen beteiligten Stakeholdern bewirken.

==== LZ 1-9: Zuständigkeit von Softwarearchitekten in organisatorischen Kontext einordnen (R3)

Softwarearchitekten kennen weitere Architekturdomänen, beispielsweise:
•	Der Fokus von Softwarearchitekten im Sinne des iSAQB und des CPSA-F:
•	Softwarearchitektur: Struktur einzelner Softwaresysteme.
•	Die folgenden Architekturebenen sich nicht inhaltlicher Fokus vom CPSA-F:
•	Unternehmens-IT-Architektur (Enterprise IT Architecture): Struktur von Anwendungs-landschaften.
•	Geschäfts- bzw. Prozessarchitektur (Business and process architecture): Struktur von u.a. Geschäftsprozessen.
•	Informationsarchitektur: systemübergreifende Struktur und Nutzung von Information und Daten.
•	Infrastruktur- bzw. Technologie-Architektur: Struktur der technischen Infrastruktur, Hardware, Netze etc.
•	Hardwarearchitektur (für hardwarenahe Systeme)
