// tag::DE[]
[[LG-04-02]]
==== LZ 04-02: Softwarearchitekturen beschreiben und kommunizieren (R1-R3)

Softwarearchitekt:innen nutzen Dokumentation zur Unterstützung bei Entwurf, Implementierung und Weiterentwicklung (auch genannt _Wartung_ oder _Evolution_) von Systemen. (R2)

Softwarearchitekt:innen können (R1):

* Architekturen entsprechend der Anliegen der Stakeholder dokumentieren und kommunizieren und dadurch unterschiedliche Zielgruppen adressieren, z.{nbsp}B. Management, Entwicklungsteams, QS, andere Softwarearchitekt:innen sowie möglicherweise zusätzliche Stakeholder
* Maßnahmen entwickeln und umsetzen, die mündliche und schriftliche Kommunikation in Einklang miteinander halten und miteinander angemessen ausbalancieren
* den Nutzen von Template-basierter Dokumentation erklären
* beschreiben, wie verschiedene Eigenschaften der Dokumentation von Spezifika des Systems, seinen Anforderungen, Risiken, dem Entwicklungsvorgehen, der Organisation oder anderen Faktoren abhängen.

Beispielsweise können Softwarearchitekt:innen die Dokumentation situationsbezogen in Umfang, Detaillierungsgrad, Format sowie Zugänglichkeit (_accessibility_) anpassen.


// end::DE[]

// tag::EN[]
[[LG-04-02]]
==== LG 04-02: Describe and Communicate Software Architectures (R1-R3)

Software architects use documentation to support the design, implementation and further development (also called _maintenance_ or _evolution_) of systems (R2)

Software architects are able to (R1):

* document and communicate architectures for corresponding stakeholder concerns, thereby addressing different target groups, e.g. management, development teams, QA, other software architects, and possibly additional stakeholders
* develop and implement measures that keep verbal and written communication aligned with one another and appropriately balanced
* explain the benefits of template-based documentation
* describe how various properties of documentation depend on specific properties of the system, its requirements, risks, development process, organization or other factors.


For example, software architects can adapt the scope, detail, format, and accessibility of documentation to the situation.

// end::EN[]
