// tag::DE[]
[[LZ-04-04]]
==== LZ 04-04 [ehemaliges LZ 3-04]: Architektursichten erläutern und anwenden (R1)
Softwarearchitekt:innen können folgende Architektursichten anwenden:

* Kontextsicht (auch genannt Kontextabgrenzung)
* Baustein- oder Komponentensicht (Aufbau des Systems aus Softwarebausteinen)
* Laufzeitsicht (dynamische Sicht, Zusammenwirken der Softwarebausteine zur Laufzeit, Zustandsmodelle)
* Verteilungs-/Deploymentsicht (Hardware und technische Infrastruktur sowie Abbildung von Softwarebausteinen auf diese Infrastruktur)

// end::DE[]

// tag::EN[]
[[LG-04-04]]
==== LG 04-04 [previously LG 3-04]: Explain and Use Architectural Views (R1)
Software architects are able to use the following architectural views:

* context view 
* building block or component view (composition of software building blocks) 
* runtime view (dynamic view, interaction between software building blocks at runtime, state machines) 
* deployment view (hardware and technical infrastructure as well as the mapping of software building blocks onto the infrastructure)

// end::EN[]
