// tag::DE[]
[[LZ-04-05]]
==== LZ 04-05 [ehemaliges LZ 3-04]: Architektursichten erläutern und anwenden (R1)
Softwarearchitekt:innen können folgende Architektursichten anwenden (siehe <<kruchten95>>, <<rozanskiwoods>>, <<starkelorz>>, <<arc42>>, <<brownc4>>):

* Kontextsicht (auch genannt Kontextabgrenzung)
  ** z.{nbsp}B. in Form von Kontextdiagrammen mit Erläuterungen darstellen
  ** externe Schnittstellen von Systemen in der Kontextabgrenzung darstellen
  ** fachlichen und technischen Kontext differenzieren

* Baustein- oder Komponentensicht (Aufbau des Systems aus Softwarebausteinen)
* Laufzeitsicht (dynamische Sicht, Zusammenwirken der Softwarebausteine zur Laufzeit, Zustandsmodelle)
* Verteilungs-/Deploymentsicht (Hardware und technische Infrastruktur sowie Abbildung von Softwarebausteinen auf diese Infrastruktur)

// end::DE[]

// tag::EN[]
[[LG-04-05]]
==== LG 04-05 [previously LG 3-04]: Explain and Use Architectural Views (R1)
Software architects are able to use the following architectural views  (see <<kruchten95>>, <<rozanskiwoods>>, <<starkelorz>>, <<arc42>>, <<brownc4>>):

* context view
  ** depict the context of systems, e.g. in the form of context diagrams with explanations
  ** represent external interfaces of systems in the context view
  ** differentiate business and technical context
* building block or component view (composition of software building blocks)
* runtime view (dynamic view, interaction between software building blocks at runtime, state machines)
* deployment view (hardware and technical infrastructure as well as the mapping of software building blocks onto the infrastructure)

// end::EN[]

