
Education based upon the _Certified Professional for Software Architecture – Foundation Level (CPSA-F)_ shall provide participants with the knowledge and skills required to design, specify and document software architectures adequate to fulfil the respective requirements for small and medium-sized systems.


=== What does "Foundation Level" cover?

As stated above, _Foundation Level_ covers small to medium-sized software systems.

Based upon their individual practical experience and existing skills, participants will learn to derive architectural decisions from an existing system vision and adequately detailed requirements.
CPSA-F trainings teach methods, principles and patterns for design, communication, documentation and evaluation of software architectures, independent of specific development processes.
The CPSA-F curriculum is technology-neutral, therefore applicable to a borad range or

Focus is education and training of the following skills:

* Discuss and reconcile fundamental architectural decisions with stakeholders from requirements, management, development, operations and test,
* understand the essential activities of software architecture, and carry out those for small- to medium sized systems,
* document and communicate software architectures based upon architectural views, architecture patterns and technical concepts

In addition, such trainings cover

* the tasks and responsibilities of software architect
* the term software architecture and its meaning
* the roles of software architects within development
* state-of-the-art methods and techniques for developing software architectures

[WARNING]
====
This is <<copyrighted,copyrighted work>>.
====