
Prerequisite: You need an up-to-date Java Runtime(tm) installed. Ubuntu's default Java 11 is not sufficient, Java 21 works.

You build the output documents with https://gradle.org[gradle]. 
That will produce both pdf and html output in German (DE) _and_ English (EN), unless you modify the configuration. 
Make sure to use the Gradle Wrapper in this repository to prevent potential build errors.


`./gradlew buildDocs`

In case you want to change the configuration, adjust the following part of `build.gradle`:

[source,groovy]
----
task buildDocs {
	group 'Documentation'
	description 'Grouping task for generating all languages in several formats'
  dependsOn "renderDE", "renderEN"
}
----

In the "renderDE" certain attributes (aka variables) are defined that configure the corresponding output.

Please note: You need to include the submodules "pdf-theme" and "html-theme" in your checkout, otherwise the build will fail. You can do that with the following commands:

. Clone the repository - including the submodule:
+
--
[source,shell]
----
Via SSH:
git clone git@github.com:isaqb-org/curriculum-foundation.git --recursive

Via HTTPS:
git clone https://github.com/isaqb-org/curriculum-foundation.git --recursive
----
--
. Initialize and update submodules with `git submodule init` and `git submodule update --recursive --remote`.